/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as TaxRouteImport } from './routes/tax'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PartnershipsRouteImport } from './routes/partnerships'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as LeavingGermanyRouteImport } from './routes/leaving-germany'
import { Route as IntegrationCoursesRouteImport } from './routes/integration-courses'
import { Route as InsuranceRouteImport } from './routes/insurance'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as GroupCoverRouteImport } from './routes/group-cover'
import { Route as ForProvidersRouteImport } from './routes/for-providers'
import { Route as DirectoryRouteImport } from './routes/directory'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BereavementCoverRouteImport } from './routes/bereavement-cover'
import { Route as BereavementRouteImport } from './routes/bereavement'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PartnersInsurersRouteImport } from './routes/partners.insurers'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalImpressumRouteImport } from './routes/legal.impressum'
import { Route as LegalCookiesRouteImport } from './routes/legal.cookies'
import { Route as LegalComplaintsRouteImport } from './routes/legal.complaints'
import { Route as GroupCoverFiduciaryClauseRouteImport } from './routes/group-cover.fiduciary-clause'
import { Route as ExpertInviteTokenRouteImport } from './routes/expert-invite.$token'
import { Route as DirectoryListYourBusinessRouteImport } from './routes/directory.list-your-business'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedExpertRouteImport } from './routes/_authenticated/expert'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAgentRouteImport } from './routes/_authenticated/agent'
import { Route as AuthenticatedPortalIndexRouteImport } from './routes/_authenticated/portal.index'
import { Route as AuthenticatedExpertIndexRouteImport } from './routes/_authenticated/expert.index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAgentIndexRouteImport } from './routes/_authenticated/agent.index'
import { Route as AuthenticatedPortalTaxRouteImport } from './routes/_authenticated/portal.tax'
import { Route as AuthenticatedPortalStudentsRouteImport } from './routes/_authenticated/portal.students'
import { Route as AuthenticatedPortalReferralsRouteImport } from './routes/_authenticated/portal.referrals'
import { Route as AuthenticatedPortalNewArrivalsRouteImport } from './routes/_authenticated/portal.new-arrivals'
import { Route as AuthenticatedPortalMedicalRouteImport } from './routes/_authenticated/portal.medical'
import { Route as AuthenticatedPortalLeadsRouteImport } from './routes/_authenticated/portal.leads'
import { Route as AuthenticatedPortalKnowledgeRouteImport } from './routes/_authenticated/portal.knowledge'
import { Route as AuthenticatedPortalInsuranceRouteImport } from './routes/_authenticated/portal.insurance'
import { Route as AuthenticatedPortalImmigrationRouteImport } from './routes/_authenticated/portal.immigration'
import { Route as AuthenticatedPortalFuneralCoverRouteImport } from './routes/_authenticated/portal.funeral-cover'
import { Route as AuthenticatedPortalFuneralRouteImport } from './routes/_authenticated/portal.funeral'
import { Route as AuthenticatedPortalFinancialsRouteImport } from './routes/_authenticated/portal.financials'
import { Route as AuthenticatedPortalExpertsRouteImport } from './routes/_authenticated/portal.experts'
import { Route as AuthenticatedPortalEscrowRouteImport } from './routes/_authenticated/portal.escrow'
import { Route as AuthenticatedPortalDirectoryRouteImport } from './routes/_authenticated/portal.directory'
import { Route as AuthenticatedPortalCapacityRouteImport } from './routes/_authenticated/portal.capacity'
import { Route as AuthenticatedPortalBenefitsRouteImport } from './routes/_authenticated/portal.benefits'
import { Route as AuthenticatedPortalAuditRouteImport } from './routes/_authenticated/portal.audit'
import { Route as AuthenticatedExpertQuotesRouteImport } from './routes/_authenticated/expert.quotes'
import { Route as AuthenticatedExpertProfileRouteImport } from './routes/_authenticated/expert.profile'
import { Route as AuthenticatedExpertPayoutsRouteImport } from './routes/_authenticated/expert.payouts'
import { Route as AuthenticatedExpertInvoicesRouteImport } from './routes/_authenticated/expert.invoices'
import { Route as AuthenticatedExpertCasesRouteImport } from './routes/_authenticated/expert.cases'
import { Route as AuthenticatedExpertAvailabilityRouteImport } from './routes/_authenticated/expert.availability'
import { Route as AuthenticatedAppUpgradeRouteImport } from './routes/_authenticated/app.upgrade'
import { Route as AuthenticatedAppStudentDiscountRouteImport } from './routes/_authenticated/app.student-discount'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as AuthenticatedAppProvidersRouteImport } from './routes/_authenticated/app.providers'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated/app.profile'
import { Route as AuthenticatedAppNotificationsRouteImport } from './routes/_authenticated/app.notifications'
import { Route as AuthenticatedAppMessagesRouteImport } from './routes/_authenticated/app.messages'
import { Route as AuthenticatedAppLocationRouteImport } from './routes/_authenticated/app.location'
import { Route as AuthenticatedAppInsuranceRouteImport } from './routes/_authenticated/app.insurance'
import { Route as AuthenticatedAppImmigrationRouteImport } from './routes/_authenticated/app.immigration'
import { Route as AuthenticatedAppDocumentsRouteImport } from './routes/_authenticated/app.documents'
import { Route as AuthenticatedAppCommunityRouteImport } from './routes/_authenticated/app.community'
import { Route as AuthenticatedAppChecklistsRouteImport } from './routes/_authenticated/app.checklists'
import { Route as AuthenticatedAppCasesRouteImport } from './routes/_authenticated/app.cases'
import { Route as AuthenticatedAppBugsRouteImport } from './routes/_authenticated/app.bugs'
import { Route as AuthenticatedAppBenefitsRouteImport } from './routes/_authenticated/app.benefits'
import { Route as AuthenticatedAppAssistantRouteImport } from './routes/_authenticated/app.assistant'
import { Route as AuthenticatedAppAlertRouteImport } from './routes/_authenticated/app.alert'
import { Route as AuthenticatedAppAccountRouteImport } from './routes/_authenticated/app.account'
import { Route as AuthenticatedAgentLinkRouteImport } from './routes/_authenticated/agent.link'
import { Route as AuthenticatedAgentLeadsRouteImport } from './routes/_authenticated/agent.leads'
import { Route as AuthenticatedAgentCommissionsRouteImport } from './routes/_authenticated/agent.commissions'
import { Route as AuthenticatedAgentClientsRouteImport } from './routes/_authenticated/agent.clients'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as AuthenticatedPortalKnowledgeSlugRouteImport } from './routes/_authenticated/portal.knowledge.$slug'
import { Route as AuthenticatedPortalGanttCaseIdRouteImport } from './routes/_authenticated/portal.gantt.$caseId'
import { Route as AuthenticatedPortalAdminUsersRouteImport } from './routes/_authenticated/portal.admin.users'
import { Route as AuthenticatedPortalAdminInviteRouteImport } from './routes/_authenticated/portal.admin.invite'
import { Route as AuthenticatedAppMessagesChannelIdRouteImport } from './routes/_authenticated/app.messages.$channelId'
import { Route as AuthenticatedAppCasesNewRouteImport } from './routes/_authenticated/app.cases.new'
import { Route as AuthenticatedAppCasesCaseIdRouteImport } from './routes/_authenticated/app.cases.$caseId'

const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxRoute = TaxRouteImport.update({
  id: '/tax',
  path: '/tax',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnershipsRoute = PartnershipsRouteImport.update({
  id: '/partnerships',
  path: '/partnerships',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const LeavingGermanyRoute = LeavingGermanyRouteImport.update({
  id: '/leaving-germany',
  path: '/leaving-germany',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationCoursesRoute = IntegrationCoursesRouteImport.update({
  id: '/integration-courses',
  path: '/integration-courses',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceRoute = InsuranceRouteImport.update({
  id: '/insurance',
  path: '/insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupCoverRoute = GroupCoverRouteImport.update({
  id: '/group-cover',
  path: '/group-cover',
  getParentRoute: () => rootRouteImport,
} as any)
const ForProvidersRoute = ForProvidersRouteImport.update({
  id: '/for-providers',
  path: '/for-providers',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BereavementCoverRoute = BereavementCoverRouteImport.update({
  id: '/bereavement-cover',
  path: '/bereavement-cover',
  getParentRoute: () => rootRouteImport,
} as any)
const BereavementRoute = BereavementRouteImport.update({
  id: '/bereavement',
  path: '/bereavement',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersInsurersRoute = PartnersInsurersRouteImport.update({
  id: '/insurers',
  path: '/insurers',
  getParentRoute: () => PartnersRoute,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LegalRoute,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LegalRoute,
} as any)
const LegalImpressumRoute = LegalImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => LegalRoute,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => LegalRoute,
} as any)
const LegalComplaintsRoute = LegalComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => LegalRoute,
} as any)
const GroupCoverFiduciaryClauseRoute =
  GroupCoverFiduciaryClauseRouteImport.update({
    id: '/fiduciary-clause',
    path: '/fiduciary-clause',
    getParentRoute: () => GroupCoverRoute,
  } as any)
const ExpertInviteTokenRoute = ExpertInviteTokenRouteImport.update({
  id: '/expert-invite/$token',
  path: '/expert-invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryListYourBusinessRoute =
  DirectoryListYourBusinessRouteImport.update({
    id: '/list-your-business',
    path: '/list-your-business',
    getParentRoute: () => DirectoryRoute,
  } as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExpertRoute = AuthenticatedExpertRouteImport.update({
  id: '/expert',
  path: '/expert',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgentRoute = AuthenticatedAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalIndexRoute =
  AuthenticatedPortalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedExpertIndexRoute =
  AuthenticatedExpertIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedExpertRoute,
  } as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAgentIndexRoute = AuthenticatedAgentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAgentRoute,
} as any)
const AuthenticatedPortalTaxRoute = AuthenticatedPortalTaxRouteImport.update({
  id: '/tax',
  path: '/tax',
  getParentRoute: () => AuthenticatedPortalRoute,
} as any)
const AuthenticatedPortalStudentsRoute =
  AuthenticatedPortalStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalReferralsRoute =
  AuthenticatedPortalReferralsRouteImport.update({
    id: '/referrals',
    path: '/referrals',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalNewArrivalsRoute =
  AuthenticatedPortalNewArrivalsRouteImport.update({
    id: '/new-arrivals',
    path: '/new-arrivals',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalMedicalRoute =
  AuthenticatedPortalMedicalRouteImport.update({
    id: '/medical',
    path: '/medical',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalLeadsRoute =
  AuthenticatedPortalLeadsRouteImport.update({
    id: '/leads',
    path: '/leads',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalKnowledgeRoute =
  AuthenticatedPortalKnowledgeRouteImport.update({
    id: '/knowledge',
    path: '/knowledge',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalInsuranceRoute =
  AuthenticatedPortalInsuranceRouteImport.update({
    id: '/insurance',
    path: '/insurance',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalImmigrationRoute =
  AuthenticatedPortalImmigrationRouteImport.update({
    id: '/immigration',
    path: '/immigration',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalFuneralCoverRoute =
  AuthenticatedPortalFuneralCoverRouteImport.update({
    id: '/funeral-cover',
    path: '/funeral-cover',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalFuneralRoute =
  AuthenticatedPortalFuneralRouteImport.update({
    id: '/funeral',
    path: '/funeral',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalFinancialsRoute =
  AuthenticatedPortalFinancialsRouteImport.update({
    id: '/financials',
    path: '/financials',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalExpertsRoute =
  AuthenticatedPortalExpertsRouteImport.update({
    id: '/experts',
    path: '/experts',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalEscrowRoute =
  AuthenticatedPortalEscrowRouteImport.update({
    id: '/escrow',
    path: '/escrow',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalDirectoryRoute =
  AuthenticatedPortalDirectoryRouteImport.update({
    id: '/directory',
    path: '/directory',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalCapacityRoute =
  AuthenticatedPortalCapacityRouteImport.update({
    id: '/capacity',
    path: '/capacity',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalBenefitsRoute =
  AuthenticatedPortalBenefitsRouteImport.update({
    id: '/benefits',
    path: '/benefits',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalAuditRoute =
  AuthenticatedPortalAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedExpertQuotesRoute =
  AuthenticatedExpertQuotesRouteImport.update({
    id: '/quotes',
    path: '/quotes',
    getParentRoute: () => AuthenticatedExpertRoute,
  } as any)
const AuthenticatedExpertProfileRoute =
  AuthenticatedExpertProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedExpertRoute,
  } as any)
const AuthenticatedExpertPayoutsRoute =
  AuthenticatedExpertPayoutsRouteImport.update({
    id: '/payouts',
    path: '/payouts',
    getParentRoute: () => AuthenticatedExpertRoute,
  } as any)
const AuthenticatedExpertInvoicesRoute =
  AuthenticatedExpertInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AuthenticatedExpertRoute,
  } as any)
const AuthenticatedExpertCasesRoute =
  AuthenticatedExpertCasesRouteImport.update({
    id: '/cases',
    path: '/cases',
    getParentRoute: () => AuthenticatedExpertRoute,
  } as any)
const AuthenticatedExpertAvailabilityRoute =
  AuthenticatedExpertAvailabilityRouteImport.update({
    id: '/availability',
    path: '/availability',
    getParentRoute: () => AuthenticatedExpertRoute,
  } as any)
const AuthenticatedAppUpgradeRoute = AuthenticatedAppUpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppStudentDiscountRoute =
  AuthenticatedAppStudentDiscountRouteImport.update({
    id: '/student-discount',
    path: '/student-discount',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProvidersRoute =
  AuthenticatedAppProvidersRouteImport.update({
    id: '/providers',
    path: '/providers',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppNotificationsRoute =
  AuthenticatedAppNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMessagesRoute =
  AuthenticatedAppMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppLocationRoute =
  AuthenticatedAppLocationRouteImport.update({
    id: '/location',
    path: '/location',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppInsuranceRoute =
  AuthenticatedAppInsuranceRouteImport.update({
    id: '/insurance',
    path: '/insurance',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppImmigrationRoute =
  AuthenticatedAppImmigrationRouteImport.update({
    id: '/immigration',
    path: '/immigration',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDocumentsRoute =
  AuthenticatedAppDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCommunityRoute =
  AuthenticatedAppCommunityRouteImport.update({
    id: '/community',
    path: '/community',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppChecklistsRoute =
  AuthenticatedAppChecklistsRouteImport.update({
    id: '/checklists',
    path: '/checklists',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCasesRoute = AuthenticatedAppCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppBugsRoute = AuthenticatedAppBugsRouteImport.update({
  id: '/bugs',
  path: '/bugs',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppBenefitsRoute =
  AuthenticatedAppBenefitsRouteImport.update({
    id: '/benefits',
    path: '/benefits',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAssistantRoute =
  AuthenticatedAppAssistantRouteImport.update({
    id: '/assistant',
    path: '/assistant',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAlertRoute = AuthenticatedAppAlertRouteImport.update({
  id: '/alert',
  path: '/alert',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAccountRoute = AuthenticatedAppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAgentLinkRoute = AuthenticatedAgentLinkRouteImport.update({
  id: '/link',
  path: '/link',
  getParentRoute: () => AuthenticatedAgentRoute,
} as any)
const AuthenticatedAgentLeadsRoute = AuthenticatedAgentLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedAgentRoute,
} as any)
const AuthenticatedAgentCommissionsRoute =
  AuthenticatedAgentCommissionsRouteImport.update({
    id: '/commissions',
    path: '/commissions',
    getParentRoute: () => AuthenticatedAgentRoute,
  } as any)
const AuthenticatedAgentClientsRoute =
  AuthenticatedAgentClientsRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => AuthenticatedAgentRoute,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPortalKnowledgeSlugRoute =
  AuthenticatedPortalKnowledgeSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedPortalKnowledgeRoute,
  } as any)
const AuthenticatedPortalGanttCaseIdRoute =
  AuthenticatedPortalGanttCaseIdRouteImport.update({
    id: '/gantt/$caseId',
    path: '/gantt/$caseId',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalAdminUsersRoute =
  AuthenticatedPortalAdminUsersRouteImport.update({
    id: '/admin/users',
    path: '/admin/users',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedPortalAdminInviteRoute =
  AuthenticatedPortalAdminInviteRouteImport.update({
    id: '/admin/invite',
    path: '/admin/invite',
    getParentRoute: () => AuthenticatedPortalRoute,
  } as any)
const AuthenticatedAppMessagesChannelIdRoute =
  AuthenticatedAppMessagesChannelIdRouteImport.update({
    id: '/$channelId',
    path: '/$channelId',
    getParentRoute: () => AuthenticatedAppMessagesRoute,
  } as any)
const AuthenticatedAppCasesNewRoute =
  AuthenticatedAppCasesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAppCasesRoute,
  } as any)
const AuthenticatedAppCasesCaseIdRoute =
  AuthenticatedAppCasesCaseIdRouteImport.update({
    id: '/$caseId',
    path: '/$caseId',
    getParentRoute: () => AuthenticatedAppCasesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bereavement': typeof BereavementRoute
  '/bereavement-cover': typeof BereavementCoverRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/directory': typeof DirectoryRouteWithChildren
  '/for-providers': typeof ForProvidersRoute
  '/group-cover': typeof GroupCoverRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/insurance': typeof InsuranceRoute
  '/integration-courses': typeof IntegrationCoursesRoute
  '/leaving-germany': typeof LeavingGermanyRoute
  '/legal': typeof LegalRouteWithChildren
  '/offline': typeof OfflineRoute
  '/partners': typeof PartnersRouteWithChildren
  '/partnerships': typeof PartnershipsRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/students': typeof StudentsRoute
  '/tax': typeof TaxRoute
  '/trust': typeof TrustRoute
  '/agent': typeof AuthenticatedAgentRouteWithChildren
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/expert': typeof AuthenticatedExpertRouteWithChildren
  '/portal': typeof AuthenticatedPortalRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/directory/list-your-business': typeof DirectoryListYourBusinessRoute
  '/expert-invite/$token': typeof ExpertInviteTokenRoute
  '/group-cover/fiduciary-clause': typeof GroupCoverFiduciaryClauseRoute
  '/legal/complaints': typeof LegalComplaintsRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/impressum': typeof LegalImpressumRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/partners/insurers': typeof PartnersInsurersRoute
  '/agent/clients': typeof AuthenticatedAgentClientsRoute
  '/agent/commissions': typeof AuthenticatedAgentCommissionsRoute
  '/agent/leads': typeof AuthenticatedAgentLeadsRoute
  '/agent/link': typeof AuthenticatedAgentLinkRoute
  '/app/account': typeof AuthenticatedAppAccountRoute
  '/app/alert': typeof AuthenticatedAppAlertRoute
  '/app/assistant': typeof AuthenticatedAppAssistantRoute
  '/app/benefits': typeof AuthenticatedAppBenefitsRoute
  '/app/bugs': typeof AuthenticatedAppBugsRoute
  '/app/cases': typeof AuthenticatedAppCasesRouteWithChildren
  '/app/checklists': typeof AuthenticatedAppChecklistsRoute
  '/app/community': typeof AuthenticatedAppCommunityRoute
  '/app/documents': typeof AuthenticatedAppDocumentsRoute
  '/app/immigration': typeof AuthenticatedAppImmigrationRoute
  '/app/insurance': typeof AuthenticatedAppInsuranceRoute
  '/app/location': typeof AuthenticatedAppLocationRoute
  '/app/messages': typeof AuthenticatedAppMessagesRouteWithChildren
  '/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/providers': typeof AuthenticatedAppProvidersRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/student-discount': typeof AuthenticatedAppStudentDiscountRoute
  '/app/upgrade': typeof AuthenticatedAppUpgradeRoute
  '/expert/availability': typeof AuthenticatedExpertAvailabilityRoute
  '/expert/cases': typeof AuthenticatedExpertCasesRoute
  '/expert/invoices': typeof AuthenticatedExpertInvoicesRoute
  '/expert/payouts': typeof AuthenticatedExpertPayoutsRoute
  '/expert/profile': typeof AuthenticatedExpertProfileRoute
  '/expert/quotes': typeof AuthenticatedExpertQuotesRoute
  '/portal/audit': typeof AuthenticatedPortalAuditRoute
  '/portal/benefits': typeof AuthenticatedPortalBenefitsRoute
  '/portal/capacity': typeof AuthenticatedPortalCapacityRoute
  '/portal/directory': typeof AuthenticatedPortalDirectoryRoute
  '/portal/escrow': typeof AuthenticatedPortalEscrowRoute
  '/portal/experts': typeof AuthenticatedPortalExpertsRoute
  '/portal/financials': typeof AuthenticatedPortalFinancialsRoute
  '/portal/funeral': typeof AuthenticatedPortalFuneralRoute
  '/portal/funeral-cover': typeof AuthenticatedPortalFuneralCoverRoute
  '/portal/immigration': typeof AuthenticatedPortalImmigrationRoute
  '/portal/insurance': typeof AuthenticatedPortalInsuranceRoute
  '/portal/knowledge': typeof AuthenticatedPortalKnowledgeRouteWithChildren
  '/portal/leads': typeof AuthenticatedPortalLeadsRoute
  '/portal/medical': typeof AuthenticatedPortalMedicalRoute
  '/portal/new-arrivals': typeof AuthenticatedPortalNewArrivalsRoute
  '/portal/referrals': typeof AuthenticatedPortalReferralsRoute
  '/portal/students': typeof AuthenticatedPortalStudentsRoute
  '/portal/tax': typeof AuthenticatedPortalTaxRoute
  '/agent/': typeof AuthenticatedAgentIndexRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/expert/': typeof AuthenticatedExpertIndexRoute
  '/portal/': typeof AuthenticatedPortalIndexRoute
  '/app/cases/$caseId': typeof AuthenticatedAppCasesCaseIdRoute
  '/app/cases/new': typeof AuthenticatedAppCasesNewRoute
  '/app/messages/$channelId': typeof AuthenticatedAppMessagesChannelIdRoute
  '/portal/admin/invite': typeof AuthenticatedPortalAdminInviteRoute
  '/portal/admin/users': typeof AuthenticatedPortalAdminUsersRoute
  '/portal/gantt/$caseId': typeof AuthenticatedPortalGanttCaseIdRoute
  '/portal/knowledge/$slug': typeof AuthenticatedPortalKnowledgeSlugRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bereavement': typeof BereavementRoute
  '/bereavement-cover': typeof BereavementCoverRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/directory': typeof DirectoryRouteWithChildren
  '/for-providers': typeof ForProvidersRoute
  '/group-cover': typeof GroupCoverRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/insurance': typeof InsuranceRoute
  '/integration-courses': typeof IntegrationCoursesRoute
  '/leaving-germany': typeof LeavingGermanyRoute
  '/legal': typeof LegalRouteWithChildren
  '/offline': typeof OfflineRoute
  '/partners': typeof PartnersRouteWithChildren
  '/partnerships': typeof PartnershipsRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/students': typeof StudentsRoute
  '/tax': typeof TaxRoute
  '/trust': typeof TrustRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/directory/list-your-business': typeof DirectoryListYourBusinessRoute
  '/expert-invite/$token': typeof ExpertInviteTokenRoute
  '/group-cover/fiduciary-clause': typeof GroupCoverFiduciaryClauseRoute
  '/legal/complaints': typeof LegalComplaintsRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/impressum': typeof LegalImpressumRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/partners/insurers': typeof PartnersInsurersRoute
  '/agent/clients': typeof AuthenticatedAgentClientsRoute
  '/agent/commissions': typeof AuthenticatedAgentCommissionsRoute
  '/agent/leads': typeof AuthenticatedAgentLeadsRoute
  '/agent/link': typeof AuthenticatedAgentLinkRoute
  '/app/account': typeof AuthenticatedAppAccountRoute
  '/app/alert': typeof AuthenticatedAppAlertRoute
  '/app/assistant': typeof AuthenticatedAppAssistantRoute
  '/app/benefits': typeof AuthenticatedAppBenefitsRoute
  '/app/bugs': typeof AuthenticatedAppBugsRoute
  '/app/cases': typeof AuthenticatedAppCasesRouteWithChildren
  '/app/checklists': typeof AuthenticatedAppChecklistsRoute
  '/app/community': typeof AuthenticatedAppCommunityRoute
  '/app/documents': typeof AuthenticatedAppDocumentsRoute
  '/app/immigration': typeof AuthenticatedAppImmigrationRoute
  '/app/insurance': typeof AuthenticatedAppInsuranceRoute
  '/app/location': typeof AuthenticatedAppLocationRoute
  '/app/messages': typeof AuthenticatedAppMessagesRouteWithChildren
  '/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/providers': typeof AuthenticatedAppProvidersRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/student-discount': typeof AuthenticatedAppStudentDiscountRoute
  '/app/upgrade': typeof AuthenticatedAppUpgradeRoute
  '/expert/availability': typeof AuthenticatedExpertAvailabilityRoute
  '/expert/cases': typeof AuthenticatedExpertCasesRoute
  '/expert/invoices': typeof AuthenticatedExpertInvoicesRoute
  '/expert/payouts': typeof AuthenticatedExpertPayoutsRoute
  '/expert/profile': typeof AuthenticatedExpertProfileRoute
  '/expert/quotes': typeof AuthenticatedExpertQuotesRoute
  '/portal/audit': typeof AuthenticatedPortalAuditRoute
  '/portal/benefits': typeof AuthenticatedPortalBenefitsRoute
  '/portal/capacity': typeof AuthenticatedPortalCapacityRoute
  '/portal/directory': typeof AuthenticatedPortalDirectoryRoute
  '/portal/escrow': typeof AuthenticatedPortalEscrowRoute
  '/portal/experts': typeof AuthenticatedPortalExpertsRoute
  '/portal/financials': typeof AuthenticatedPortalFinancialsRoute
  '/portal/funeral': typeof AuthenticatedPortalFuneralRoute
  '/portal/funeral-cover': typeof AuthenticatedPortalFuneralCoverRoute
  '/portal/immigration': typeof AuthenticatedPortalImmigrationRoute
  '/portal/insurance': typeof AuthenticatedPortalInsuranceRoute
  '/portal/knowledge': typeof AuthenticatedPortalKnowledgeRouteWithChildren
  '/portal/leads': typeof AuthenticatedPortalLeadsRoute
  '/portal/medical': typeof AuthenticatedPortalMedicalRoute
  '/portal/new-arrivals': typeof AuthenticatedPortalNewArrivalsRoute
  '/portal/referrals': typeof AuthenticatedPortalReferralsRoute
  '/portal/students': typeof AuthenticatedPortalStudentsRoute
  '/portal/tax': typeof AuthenticatedPortalTaxRoute
  '/agent': typeof AuthenticatedAgentIndexRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/expert': typeof AuthenticatedExpertIndexRoute
  '/portal': typeof AuthenticatedPortalIndexRoute
  '/app/cases/$caseId': typeof AuthenticatedAppCasesCaseIdRoute
  '/app/cases/new': typeof AuthenticatedAppCasesNewRoute
  '/app/messages/$channelId': typeof AuthenticatedAppMessagesChannelIdRoute
  '/portal/admin/invite': typeof AuthenticatedPortalAdminInviteRoute
  '/portal/admin/users': typeof AuthenticatedPortalAdminUsersRoute
  '/portal/gantt/$caseId': typeof AuthenticatedPortalGanttCaseIdRoute
  '/portal/knowledge/$slug': typeof AuthenticatedPortalKnowledgeSlugRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/bereavement': typeof BereavementRoute
  '/bereavement-cover': typeof BereavementCoverRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/directory': typeof DirectoryRouteWithChildren
  '/for-providers': typeof ForProvidersRoute
  '/group-cover': typeof GroupCoverRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/insurance': typeof InsuranceRoute
  '/integration-courses': typeof IntegrationCoursesRoute
  '/leaving-germany': typeof LeavingGermanyRoute
  '/legal': typeof LegalRouteWithChildren
  '/offline': typeof OfflineRoute
  '/partners': typeof PartnersRouteWithChildren
  '/partnerships': typeof PartnershipsRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/students': typeof StudentsRoute
  '/tax': typeof TaxRoute
  '/trust': typeof TrustRoute
  '/_authenticated/agent': typeof AuthenticatedAgentRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/expert': typeof AuthenticatedExpertRouteWithChildren
  '/_authenticated/portal': typeof AuthenticatedPortalRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/directory/list-your-business': typeof DirectoryListYourBusinessRoute
  '/expert-invite/$token': typeof ExpertInviteTokenRoute
  '/group-cover/fiduciary-clause': typeof GroupCoverFiduciaryClauseRoute
  '/legal/complaints': typeof LegalComplaintsRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/impressum': typeof LegalImpressumRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/partners/insurers': typeof PartnersInsurersRoute
  '/_authenticated/agent/clients': typeof AuthenticatedAgentClientsRoute
  '/_authenticated/agent/commissions': typeof AuthenticatedAgentCommissionsRoute
  '/_authenticated/agent/leads': typeof AuthenticatedAgentLeadsRoute
  '/_authenticated/agent/link': typeof AuthenticatedAgentLinkRoute
  '/_authenticated/app/account': typeof AuthenticatedAppAccountRoute
  '/_authenticated/app/alert': typeof AuthenticatedAppAlertRoute
  '/_authenticated/app/assistant': typeof AuthenticatedAppAssistantRoute
  '/_authenticated/app/benefits': typeof AuthenticatedAppBenefitsRoute
  '/_authenticated/app/bugs': typeof AuthenticatedAppBugsRoute
  '/_authenticated/app/cases': typeof AuthenticatedAppCasesRouteWithChildren
  '/_authenticated/app/checklists': typeof AuthenticatedAppChecklistsRoute
  '/_authenticated/app/community': typeof AuthenticatedAppCommunityRoute
  '/_authenticated/app/documents': typeof AuthenticatedAppDocumentsRoute
  '/_authenticated/app/immigration': typeof AuthenticatedAppImmigrationRoute
  '/_authenticated/app/insurance': typeof AuthenticatedAppInsuranceRoute
  '/_authenticated/app/location': typeof AuthenticatedAppLocationRoute
  '/_authenticated/app/messages': typeof AuthenticatedAppMessagesRouteWithChildren
  '/_authenticated/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/_authenticated/app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/app/providers': typeof AuthenticatedAppProvidersRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/student-discount': typeof AuthenticatedAppStudentDiscountRoute
  '/_authenticated/app/upgrade': typeof AuthenticatedAppUpgradeRoute
  '/_authenticated/expert/availability': typeof AuthenticatedExpertAvailabilityRoute
  '/_authenticated/expert/cases': typeof AuthenticatedExpertCasesRoute
  '/_authenticated/expert/invoices': typeof AuthenticatedExpertInvoicesRoute
  '/_authenticated/expert/payouts': typeof AuthenticatedExpertPayoutsRoute
  '/_authenticated/expert/profile': typeof AuthenticatedExpertProfileRoute
  '/_authenticated/expert/quotes': typeof AuthenticatedExpertQuotesRoute
  '/_authenticated/portal/audit': typeof AuthenticatedPortalAuditRoute
  '/_authenticated/portal/benefits': typeof AuthenticatedPortalBenefitsRoute
  '/_authenticated/portal/capacity': typeof AuthenticatedPortalCapacityRoute
  '/_authenticated/portal/directory': typeof AuthenticatedPortalDirectoryRoute
  '/_authenticated/portal/escrow': typeof AuthenticatedPortalEscrowRoute
  '/_authenticated/portal/experts': typeof AuthenticatedPortalExpertsRoute
  '/_authenticated/portal/financials': typeof AuthenticatedPortalFinancialsRoute
  '/_authenticated/portal/funeral': typeof AuthenticatedPortalFuneralRoute
  '/_authenticated/portal/funeral-cover': typeof AuthenticatedPortalFuneralCoverRoute
  '/_authenticated/portal/immigration': typeof AuthenticatedPortalImmigrationRoute
  '/_authenticated/portal/insurance': typeof AuthenticatedPortalInsuranceRoute
  '/_authenticated/portal/knowledge': typeof AuthenticatedPortalKnowledgeRouteWithChildren
  '/_authenticated/portal/leads': typeof AuthenticatedPortalLeadsRoute
  '/_authenticated/portal/medical': typeof AuthenticatedPortalMedicalRoute
  '/_authenticated/portal/new-arrivals': typeof AuthenticatedPortalNewArrivalsRoute
  '/_authenticated/portal/referrals': typeof AuthenticatedPortalReferralsRoute
  '/_authenticated/portal/students': typeof AuthenticatedPortalStudentsRoute
  '/_authenticated/portal/tax': typeof AuthenticatedPortalTaxRoute
  '/_authenticated/agent/': typeof AuthenticatedAgentIndexRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/expert/': typeof AuthenticatedExpertIndexRoute
  '/_authenticated/portal/': typeof AuthenticatedPortalIndexRoute
  '/_authenticated/app/cases/$caseId': typeof AuthenticatedAppCasesCaseIdRoute
  '/_authenticated/app/cases/new': typeof AuthenticatedAppCasesNewRoute
  '/_authenticated/app/messages/$channelId': typeof AuthenticatedAppMessagesChannelIdRoute
  '/_authenticated/portal/admin/invite': typeof AuthenticatedPortalAdminInviteRoute
  '/_authenticated/portal/admin/users': typeof AuthenticatedPortalAdminUsersRoute
  '/_authenticated/portal/gantt/$caseId': typeof AuthenticatedPortalGanttCaseIdRoute
  '/_authenticated/portal/knowledge/$slug': typeof AuthenticatedPortalKnowledgeSlugRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bereavement'
    | '/bereavement-cover'
    | '/blog'
    | '/contact'
    | '/directory'
    | '/for-providers'
    | '/group-cover'
    | '/how-it-works'
    | '/insurance'
    | '/integration-courses'
    | '/leaving-germany'
    | '/legal'
    | '/offline'
    | '/partners'
    | '/partnerships'
    | '/pricing'
    | '/reset-password'
    | '/services'
    | '/sitemap.xml'
    | '/students'
    | '/tax'
    | '/trust'
    | '/agent'
    | '/app'
    | '/expert'
    | '/portal'
    | '/blog/$slug'
    | '/checkout/return'
    | '/directory/list-your-business'
    | '/expert-invite/$token'
    | '/group-cover/fiduciary-clause'
    | '/legal/complaints'
    | '/legal/cookies'
    | '/legal/impressum'
    | '/legal/privacy'
    | '/legal/terms'
    | '/partners/insurers'
    | '/agent/clients'
    | '/agent/commissions'
    | '/agent/leads'
    | '/agent/link'
    | '/app/account'
    | '/app/alert'
    | '/app/assistant'
    | '/app/benefits'
    | '/app/bugs'
    | '/app/cases'
    | '/app/checklists'
    | '/app/community'
    | '/app/documents'
    | '/app/immigration'
    | '/app/insurance'
    | '/app/location'
    | '/app/messages'
    | '/app/notifications'
    | '/app/profile'
    | '/app/providers'
    | '/app/settings'
    | '/app/student-discount'
    | '/app/upgrade'
    | '/expert/availability'
    | '/expert/cases'
    | '/expert/invoices'
    | '/expert/payouts'
    | '/expert/profile'
    | '/expert/quotes'
    | '/portal/audit'
    | '/portal/benefits'
    | '/portal/capacity'
    | '/portal/directory'
    | '/portal/escrow'
    | '/portal/experts'
    | '/portal/financials'
    | '/portal/funeral'
    | '/portal/funeral-cover'
    | '/portal/immigration'
    | '/portal/insurance'
    | '/portal/knowledge'
    | '/portal/leads'
    | '/portal/medical'
    | '/portal/new-arrivals'
    | '/portal/referrals'
    | '/portal/students'
    | '/portal/tax'
    | '/agent/'
    | '/app/'
    | '/expert/'
    | '/portal/'
    | '/app/cases/$caseId'
    | '/app/cases/new'
    | '/app/messages/$channelId'
    | '/portal/admin/invite'
    | '/portal/admin/users'
    | '/portal/gantt/$caseId'
    | '/portal/knowledge/$slug'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bereavement'
    | '/bereavement-cover'
    | '/blog'
    | '/contact'
    | '/directory'
    | '/for-providers'
    | '/group-cover'
    | '/how-it-works'
    | '/insurance'
    | '/integration-courses'
    | '/leaving-germany'
    | '/legal'
    | '/offline'
    | '/partners'
    | '/partnerships'
    | '/pricing'
    | '/reset-password'
    | '/services'
    | '/sitemap.xml'
    | '/students'
    | '/tax'
    | '/trust'
    | '/blog/$slug'
    | '/checkout/return'
    | '/directory/list-your-business'
    | '/expert-invite/$token'
    | '/group-cover/fiduciary-clause'
    | '/legal/complaints'
    | '/legal/cookies'
    | '/legal/impressum'
    | '/legal/privacy'
    | '/legal/terms'
    | '/partners/insurers'
    | '/agent/clients'
    | '/agent/commissions'
    | '/agent/leads'
    | '/agent/link'
    | '/app/account'
    | '/app/alert'
    | '/app/assistant'
    | '/app/benefits'
    | '/app/bugs'
    | '/app/cases'
    | '/app/checklists'
    | '/app/community'
    | '/app/documents'
    | '/app/immigration'
    | '/app/insurance'
    | '/app/location'
    | '/app/messages'
    | '/app/notifications'
    | '/app/profile'
    | '/app/providers'
    | '/app/settings'
    | '/app/student-discount'
    | '/app/upgrade'
    | '/expert/availability'
    | '/expert/cases'
    | '/expert/invoices'
    | '/expert/payouts'
    | '/expert/profile'
    | '/expert/quotes'
    | '/portal/audit'
    | '/portal/benefits'
    | '/portal/capacity'
    | '/portal/directory'
    | '/portal/escrow'
    | '/portal/experts'
    | '/portal/financials'
    | '/portal/funeral'
    | '/portal/funeral-cover'
    | '/portal/immigration'
    | '/portal/insurance'
    | '/portal/knowledge'
    | '/portal/leads'
    | '/portal/medical'
    | '/portal/new-arrivals'
    | '/portal/referrals'
    | '/portal/students'
    | '/portal/tax'
    | '/agent'
    | '/app'
    | '/expert'
    | '/portal'
    | '/app/cases/$caseId'
    | '/app/cases/new'
    | '/app/messages/$channelId'
    | '/portal/admin/invite'
    | '/portal/admin/users'
    | '/portal/gantt/$caseId'
    | '/portal/knowledge/$slug'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/bereavement'
    | '/bereavement-cover'
    | '/blog'
    | '/contact'
    | '/directory'
    | '/for-providers'
    | '/group-cover'
    | '/how-it-works'
    | '/insurance'
    | '/integration-courses'
    | '/leaving-germany'
    | '/legal'
    | '/offline'
    | '/partners'
    | '/partnerships'
    | '/pricing'
    | '/reset-password'
    | '/services'
    | '/sitemap.xml'
    | '/students'
    | '/tax'
    | '/trust'
    | '/_authenticated/agent'
    | '/_authenticated/app'
    | '/_authenticated/expert'
    | '/_authenticated/portal'
    | '/blog/$slug'
    | '/checkout/return'
    | '/directory/list-your-business'
    | '/expert-invite/$token'
    | '/group-cover/fiduciary-clause'
    | '/legal/complaints'
    | '/legal/cookies'
    | '/legal/impressum'
    | '/legal/privacy'
    | '/legal/terms'
    | '/partners/insurers'
    | '/_authenticated/agent/clients'
    | '/_authenticated/agent/commissions'
    | '/_authenticated/agent/leads'
    | '/_authenticated/agent/link'
    | '/_authenticated/app/account'
    | '/_authenticated/app/alert'
    | '/_authenticated/app/assistant'
    | '/_authenticated/app/benefits'
    | '/_authenticated/app/bugs'
    | '/_authenticated/app/cases'
    | '/_authenticated/app/checklists'
    | '/_authenticated/app/community'
    | '/_authenticated/app/documents'
    | '/_authenticated/app/immigration'
    | '/_authenticated/app/insurance'
    | '/_authenticated/app/location'
    | '/_authenticated/app/messages'
    | '/_authenticated/app/notifications'
    | '/_authenticated/app/profile'
    | '/_authenticated/app/providers'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/student-discount'
    | '/_authenticated/app/upgrade'
    | '/_authenticated/expert/availability'
    | '/_authenticated/expert/cases'
    | '/_authenticated/expert/invoices'
    | '/_authenticated/expert/payouts'
    | '/_authenticated/expert/profile'
    | '/_authenticated/expert/quotes'
    | '/_authenticated/portal/audit'
    | '/_authenticated/portal/benefits'
    | '/_authenticated/portal/capacity'
    | '/_authenticated/portal/directory'
    | '/_authenticated/portal/escrow'
    | '/_authenticated/portal/experts'
    | '/_authenticated/portal/financials'
    | '/_authenticated/portal/funeral'
    | '/_authenticated/portal/funeral-cover'
    | '/_authenticated/portal/immigration'
    | '/_authenticated/portal/insurance'
    | '/_authenticated/portal/knowledge'
    | '/_authenticated/portal/leads'
    | '/_authenticated/portal/medical'
    | '/_authenticated/portal/new-arrivals'
    | '/_authenticated/portal/referrals'
    | '/_authenticated/portal/students'
    | '/_authenticated/portal/tax'
    | '/_authenticated/agent/'
    | '/_authenticated/app/'
    | '/_authenticated/expert/'
    | '/_authenticated/portal/'
    | '/_authenticated/app/cases/$caseId'
    | '/_authenticated/app/cases/new'
    | '/_authenticated/app/messages/$channelId'
    | '/_authenticated/portal/admin/invite'
    | '/_authenticated/portal/admin/users'
    | '/_authenticated/portal/gantt/$caseId'
    | '/_authenticated/portal/knowledge/$slug'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BereavementRoute: typeof BereavementRoute
  BereavementCoverRoute: typeof BereavementCoverRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  DirectoryRoute: typeof DirectoryRouteWithChildren
  ForProvidersRoute: typeof ForProvidersRoute
  GroupCoverRoute: typeof GroupCoverRouteWithChildren
  HowItWorksRoute: typeof HowItWorksRoute
  InsuranceRoute: typeof InsuranceRoute
  IntegrationCoursesRoute: typeof IntegrationCoursesRoute
  LeavingGermanyRoute: typeof LeavingGermanyRoute
  LegalRoute: typeof LegalRouteWithChildren
  OfflineRoute: typeof OfflineRoute
  PartnersRoute: typeof PartnersRouteWithChildren
  PartnershipsRoute: typeof PartnershipsRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudentsRoute: typeof StudentsRoute
  TaxRoute: typeof TaxRoute
  TrustRoute: typeof TrustRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  ExpertInviteTokenRoute: typeof ExpertInviteTokenRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tax': {
      id: '/tax'
      path: '/tax'
      fullPath: '/tax'
      preLoaderRoute: typeof TaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partnerships': {
      id: '/partnerships'
      path: '/partnerships'
      fullPath: '/partnerships'
      preLoaderRoute: typeof PartnershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaving-germany': {
      id: '/leaving-germany'
      path: '/leaving-germany'
      fullPath: '/leaving-germany'
      preLoaderRoute: typeof LeavingGermanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration-courses': {
      id: '/integration-courses'
      path: '/integration-courses'
      fullPath: '/integration-courses'
      preLoaderRoute: typeof IntegrationCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance': {
      id: '/insurance'
      path: '/insurance'
      fullPath: '/insurance'
      preLoaderRoute: typeof InsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group-cover': {
      id: '/group-cover'
      path: '/group-cover'
      fullPath: '/group-cover'
      preLoaderRoute: typeof GroupCoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-providers': {
      id: '/for-providers'
      path: '/for-providers'
      fullPath: '/for-providers'
      preLoaderRoute: typeof ForProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bereavement-cover': {
      id: '/bereavement-cover'
      path: '/bereavement-cover'
      fullPath: '/bereavement-cover'
      preLoaderRoute: typeof BereavementCoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bereavement': {
      id: '/bereavement'
      path: '/bereavement'
      fullPath: '/bereavement'
      preLoaderRoute: typeof BereavementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners/insurers': {
      id: '/partners/insurers'
      path: '/insurers'
      fullPath: '/partners/insurers'
      preLoaderRoute: typeof PartnersInsurersRouteImport
      parentRoute: typeof PartnersRoute
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/impressum': {
      id: '/legal/impressum'
      path: '/impressum'
      fullPath: '/legal/impressum'
      preLoaderRoute: typeof LegalImpressumRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/complaints': {
      id: '/legal/complaints'
      path: '/complaints'
      fullPath: '/legal/complaints'
      preLoaderRoute: typeof LegalComplaintsRouteImport
      parentRoute: typeof LegalRoute
    }
    '/group-cover/fiduciary-clause': {
      id: '/group-cover/fiduciary-clause'
      path: '/fiduciary-clause'
      fullPath: '/group-cover/fiduciary-clause'
      preLoaderRoute: typeof GroupCoverFiduciaryClauseRouteImport
      parentRoute: typeof GroupCoverRoute
    }
    '/expert-invite/$token': {
      id: '/expert-invite/$token'
      path: '/expert-invite/$token'
      fullPath: '/expert-invite/$token'
      preLoaderRoute: typeof ExpertInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory/list-your-business': {
      id: '/directory/list-your-business'
      path: '/list-your-business'
      fullPath: '/directory/list-your-business'
      preLoaderRoute: typeof DirectoryListYourBusinessRouteImport
      parentRoute: typeof DirectoryRoute
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expert': {
      id: '/_authenticated/expert'
      path: '/expert'
      fullPath: '/expert'
      preLoaderRoute: typeof AuthenticatedExpertRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agent': {
      id: '/_authenticated/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AuthenticatedAgentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/': {
      id: '/_authenticated/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof AuthenticatedPortalIndexRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/expert/': {
      id: '/_authenticated/expert/'
      path: '/'
      fullPath: '/expert/'
      preLoaderRoute: typeof AuthenticatedExpertIndexRouteImport
      parentRoute: typeof AuthenticatedExpertRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/agent/': {
      id: '/_authenticated/agent/'
      path: '/'
      fullPath: '/agent/'
      preLoaderRoute: typeof AuthenticatedAgentIndexRouteImport
      parentRoute: typeof AuthenticatedAgentRoute
    }
    '/_authenticated/portal/tax': {
      id: '/_authenticated/portal/tax'
      path: '/tax'
      fullPath: '/portal/tax'
      preLoaderRoute: typeof AuthenticatedPortalTaxRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/students': {
      id: '/_authenticated/portal/students'
      path: '/students'
      fullPath: '/portal/students'
      preLoaderRoute: typeof AuthenticatedPortalStudentsRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/referrals': {
      id: '/_authenticated/portal/referrals'
      path: '/referrals'
      fullPath: '/portal/referrals'
      preLoaderRoute: typeof AuthenticatedPortalReferralsRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/new-arrivals': {
      id: '/_authenticated/portal/new-arrivals'
      path: '/new-arrivals'
      fullPath: '/portal/new-arrivals'
      preLoaderRoute: typeof AuthenticatedPortalNewArrivalsRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/medical': {
      id: '/_authenticated/portal/medical'
      path: '/medical'
      fullPath: '/portal/medical'
      preLoaderRoute: typeof AuthenticatedPortalMedicalRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/leads': {
      id: '/_authenticated/portal/leads'
      path: '/leads'
      fullPath: '/portal/leads'
      preLoaderRoute: typeof AuthenticatedPortalLeadsRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/knowledge': {
      id: '/_authenticated/portal/knowledge'
      path: '/knowledge'
      fullPath: '/portal/knowledge'
      preLoaderRoute: typeof AuthenticatedPortalKnowledgeRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/insurance': {
      id: '/_authenticated/portal/insurance'
      path: '/insurance'
      fullPath: '/portal/insurance'
      preLoaderRoute: typeof AuthenticatedPortalInsuranceRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/immigration': {
      id: '/_authenticated/portal/immigration'
      path: '/immigration'
      fullPath: '/portal/immigration'
      preLoaderRoute: typeof AuthenticatedPortalImmigrationRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/funeral-cover': {
      id: '/_authenticated/portal/funeral-cover'
      path: '/funeral-cover'
      fullPath: '/portal/funeral-cover'
      preLoaderRoute: typeof AuthenticatedPortalFuneralCoverRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/funeral': {
      id: '/_authenticated/portal/funeral'
      path: '/funeral'
      fullPath: '/portal/funeral'
      preLoaderRoute: typeof AuthenticatedPortalFuneralRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/financials': {
      id: '/_authenticated/portal/financials'
      path: '/financials'
      fullPath: '/portal/financials'
      preLoaderRoute: typeof AuthenticatedPortalFinancialsRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/experts': {
      id: '/_authenticated/portal/experts'
      path: '/experts'
      fullPath: '/portal/experts'
      preLoaderRoute: typeof AuthenticatedPortalExpertsRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/escrow': {
      id: '/_authenticated/portal/escrow'
      path: '/escrow'
      fullPath: '/portal/escrow'
      preLoaderRoute: typeof AuthenticatedPortalEscrowRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/directory': {
      id: '/_authenticated/portal/directory'
      path: '/directory'
      fullPath: '/portal/directory'
      preLoaderRoute: typeof AuthenticatedPortalDirectoryRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/capacity': {
      id: '/_authenticated/portal/capacity'
      path: '/capacity'
      fullPath: '/portal/capacity'
      preLoaderRoute: typeof AuthenticatedPortalCapacityRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/benefits': {
      id: '/_authenticated/portal/benefits'
      path: '/benefits'
      fullPath: '/portal/benefits'
      preLoaderRoute: typeof AuthenticatedPortalBenefitsRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/audit': {
      id: '/_authenticated/portal/audit'
      path: '/audit'
      fullPath: '/portal/audit'
      preLoaderRoute: typeof AuthenticatedPortalAuditRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/expert/quotes': {
      id: '/_authenticated/expert/quotes'
      path: '/quotes'
      fullPath: '/expert/quotes'
      preLoaderRoute: typeof AuthenticatedExpertQuotesRouteImport
      parentRoute: typeof AuthenticatedExpertRoute
    }
    '/_authenticated/expert/profile': {
      id: '/_authenticated/expert/profile'
      path: '/profile'
      fullPath: '/expert/profile'
      preLoaderRoute: typeof AuthenticatedExpertProfileRouteImport
      parentRoute: typeof AuthenticatedExpertRoute
    }
    '/_authenticated/expert/payouts': {
      id: '/_authenticated/expert/payouts'
      path: '/payouts'
      fullPath: '/expert/payouts'
      preLoaderRoute: typeof AuthenticatedExpertPayoutsRouteImport
      parentRoute: typeof AuthenticatedExpertRoute
    }
    '/_authenticated/expert/invoices': {
      id: '/_authenticated/expert/invoices'
      path: '/invoices'
      fullPath: '/expert/invoices'
      preLoaderRoute: typeof AuthenticatedExpertInvoicesRouteImport
      parentRoute: typeof AuthenticatedExpertRoute
    }
    '/_authenticated/expert/cases': {
      id: '/_authenticated/expert/cases'
      path: '/cases'
      fullPath: '/expert/cases'
      preLoaderRoute: typeof AuthenticatedExpertCasesRouteImport
      parentRoute: typeof AuthenticatedExpertRoute
    }
    '/_authenticated/expert/availability': {
      id: '/_authenticated/expert/availability'
      path: '/availability'
      fullPath: '/expert/availability'
      preLoaderRoute: typeof AuthenticatedExpertAvailabilityRouteImport
      parentRoute: typeof AuthenticatedExpertRoute
    }
    '/_authenticated/app/upgrade': {
      id: '/_authenticated/app/upgrade'
      path: '/upgrade'
      fullPath: '/app/upgrade'
      preLoaderRoute: typeof AuthenticatedAppUpgradeRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/student-discount': {
      id: '/_authenticated/app/student-discount'
      path: '/student-discount'
      fullPath: '/app/student-discount'
      preLoaderRoute: typeof AuthenticatedAppStudentDiscountRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/providers': {
      id: '/_authenticated/app/providers'
      path: '/providers'
      fullPath: '/app/providers'
      preLoaderRoute: typeof AuthenticatedAppProvidersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/profile': {
      id: '/_authenticated/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/notifications': {
      id: '/_authenticated/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AuthenticatedAppNotificationsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/messages': {
      id: '/_authenticated/app/messages'
      path: '/messages'
      fullPath: '/app/messages'
      preLoaderRoute: typeof AuthenticatedAppMessagesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/location': {
      id: '/_authenticated/app/location'
      path: '/location'
      fullPath: '/app/location'
      preLoaderRoute: typeof AuthenticatedAppLocationRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/insurance': {
      id: '/_authenticated/app/insurance'
      path: '/insurance'
      fullPath: '/app/insurance'
      preLoaderRoute: typeof AuthenticatedAppInsuranceRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/immigration': {
      id: '/_authenticated/app/immigration'
      path: '/immigration'
      fullPath: '/app/immigration'
      preLoaderRoute: typeof AuthenticatedAppImmigrationRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/documents': {
      id: '/_authenticated/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AuthenticatedAppDocumentsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/community': {
      id: '/_authenticated/app/community'
      path: '/community'
      fullPath: '/app/community'
      preLoaderRoute: typeof AuthenticatedAppCommunityRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/checklists': {
      id: '/_authenticated/app/checklists'
      path: '/checklists'
      fullPath: '/app/checklists'
      preLoaderRoute: typeof AuthenticatedAppChecklistsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/cases': {
      id: '/_authenticated/app/cases'
      path: '/cases'
      fullPath: '/app/cases'
      preLoaderRoute: typeof AuthenticatedAppCasesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/bugs': {
      id: '/_authenticated/app/bugs'
      path: '/bugs'
      fullPath: '/app/bugs'
      preLoaderRoute: typeof AuthenticatedAppBugsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/benefits': {
      id: '/_authenticated/app/benefits'
      path: '/benefits'
      fullPath: '/app/benefits'
      preLoaderRoute: typeof AuthenticatedAppBenefitsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/assistant': {
      id: '/_authenticated/app/assistant'
      path: '/assistant'
      fullPath: '/app/assistant'
      preLoaderRoute: typeof AuthenticatedAppAssistantRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/alert': {
      id: '/_authenticated/app/alert'
      path: '/alert'
      fullPath: '/app/alert'
      preLoaderRoute: typeof AuthenticatedAppAlertRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/account': {
      id: '/_authenticated/app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AuthenticatedAppAccountRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/agent/link': {
      id: '/_authenticated/agent/link'
      path: '/link'
      fullPath: '/agent/link'
      preLoaderRoute: typeof AuthenticatedAgentLinkRouteImport
      parentRoute: typeof AuthenticatedAgentRoute
    }
    '/_authenticated/agent/leads': {
      id: '/_authenticated/agent/leads'
      path: '/leads'
      fullPath: '/agent/leads'
      preLoaderRoute: typeof AuthenticatedAgentLeadsRouteImport
      parentRoute: typeof AuthenticatedAgentRoute
    }
    '/_authenticated/agent/commissions': {
      id: '/_authenticated/agent/commissions'
      path: '/commissions'
      fullPath: '/agent/commissions'
      preLoaderRoute: typeof AuthenticatedAgentCommissionsRouteImport
      parentRoute: typeof AuthenticatedAgentRoute
    }
    '/_authenticated/agent/clients': {
      id: '/_authenticated/agent/clients'
      path: '/clients'
      fullPath: '/agent/clients'
      preLoaderRoute: typeof AuthenticatedAgentClientsRouteImport
      parentRoute: typeof AuthenticatedAgentRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal/knowledge/$slug': {
      id: '/_authenticated/portal/knowledge/$slug'
      path: '/$slug'
      fullPath: '/portal/knowledge/$slug'
      preLoaderRoute: typeof AuthenticatedPortalKnowledgeSlugRouteImport
      parentRoute: typeof AuthenticatedPortalKnowledgeRoute
    }
    '/_authenticated/portal/gantt/$caseId': {
      id: '/_authenticated/portal/gantt/$caseId'
      path: '/gantt/$caseId'
      fullPath: '/portal/gantt/$caseId'
      preLoaderRoute: typeof AuthenticatedPortalGanttCaseIdRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/admin/users': {
      id: '/_authenticated/portal/admin/users'
      path: '/admin/users'
      fullPath: '/portal/admin/users'
      preLoaderRoute: typeof AuthenticatedPortalAdminUsersRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/portal/admin/invite': {
      id: '/_authenticated/portal/admin/invite'
      path: '/admin/invite'
      fullPath: '/portal/admin/invite'
      preLoaderRoute: typeof AuthenticatedPortalAdminInviteRouteImport
      parentRoute: typeof AuthenticatedPortalRoute
    }
    '/_authenticated/app/messages/$channelId': {
      id: '/_authenticated/app/messages/$channelId'
      path: '/$channelId'
      fullPath: '/app/messages/$channelId'
      preLoaderRoute: typeof AuthenticatedAppMessagesChannelIdRouteImport
      parentRoute: typeof AuthenticatedAppMessagesRoute
    }
    '/_authenticated/app/cases/new': {
      id: '/_authenticated/app/cases/new'
      path: '/new'
      fullPath: '/app/cases/new'
      preLoaderRoute: typeof AuthenticatedAppCasesNewRouteImport
      parentRoute: typeof AuthenticatedAppCasesRoute
    }
    '/_authenticated/app/cases/$caseId': {
      id: '/_authenticated/app/cases/$caseId'
      path: '/$caseId'
      fullPath: '/app/cases/$caseId'
      preLoaderRoute: typeof AuthenticatedAppCasesCaseIdRouteImport
      parentRoute: typeof AuthenticatedAppCasesRoute
    }
  }
}

interface AuthenticatedAgentRouteChildren {
  AuthenticatedAgentClientsRoute: typeof AuthenticatedAgentClientsRoute
  AuthenticatedAgentCommissionsRoute: typeof AuthenticatedAgentCommissionsRoute
  AuthenticatedAgentLeadsRoute: typeof AuthenticatedAgentLeadsRoute
  AuthenticatedAgentLinkRoute: typeof AuthenticatedAgentLinkRoute
  AuthenticatedAgentIndexRoute: typeof AuthenticatedAgentIndexRoute
}

const AuthenticatedAgentRouteChildren: AuthenticatedAgentRouteChildren = {
  AuthenticatedAgentClientsRoute: AuthenticatedAgentClientsRoute,
  AuthenticatedAgentCommissionsRoute: AuthenticatedAgentCommissionsRoute,
  AuthenticatedAgentLeadsRoute: AuthenticatedAgentLeadsRoute,
  AuthenticatedAgentLinkRoute: AuthenticatedAgentLinkRoute,
  AuthenticatedAgentIndexRoute: AuthenticatedAgentIndexRoute,
}

const AuthenticatedAgentRouteWithChildren =
  AuthenticatedAgentRoute._addFileChildren(AuthenticatedAgentRouteChildren)

interface AuthenticatedAppCasesRouteChildren {
  AuthenticatedAppCasesCaseIdRoute: typeof AuthenticatedAppCasesCaseIdRoute
  AuthenticatedAppCasesNewRoute: typeof AuthenticatedAppCasesNewRoute
}

const AuthenticatedAppCasesRouteChildren: AuthenticatedAppCasesRouteChildren = {
  AuthenticatedAppCasesCaseIdRoute: AuthenticatedAppCasesCaseIdRoute,
  AuthenticatedAppCasesNewRoute: AuthenticatedAppCasesNewRoute,
}

const AuthenticatedAppCasesRouteWithChildren =
  AuthenticatedAppCasesRoute._addFileChildren(
    AuthenticatedAppCasesRouteChildren,
  )

interface AuthenticatedAppMessagesRouteChildren {
  AuthenticatedAppMessagesChannelIdRoute: typeof AuthenticatedAppMessagesChannelIdRoute
}

const AuthenticatedAppMessagesRouteChildren: AuthenticatedAppMessagesRouteChildren =
  {
    AuthenticatedAppMessagesChannelIdRoute:
      AuthenticatedAppMessagesChannelIdRoute,
  }

const AuthenticatedAppMessagesRouteWithChildren =
  AuthenticatedAppMessagesRoute._addFileChildren(
    AuthenticatedAppMessagesRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAccountRoute: typeof AuthenticatedAppAccountRoute
  AuthenticatedAppAlertRoute: typeof AuthenticatedAppAlertRoute
  AuthenticatedAppAssistantRoute: typeof AuthenticatedAppAssistantRoute
  AuthenticatedAppBenefitsRoute: typeof AuthenticatedAppBenefitsRoute
  AuthenticatedAppBugsRoute: typeof AuthenticatedAppBugsRoute
  AuthenticatedAppCasesRoute: typeof AuthenticatedAppCasesRouteWithChildren
  AuthenticatedAppChecklistsRoute: typeof AuthenticatedAppChecklistsRoute
  AuthenticatedAppCommunityRoute: typeof AuthenticatedAppCommunityRoute
  AuthenticatedAppDocumentsRoute: typeof AuthenticatedAppDocumentsRoute
  AuthenticatedAppImmigrationRoute: typeof AuthenticatedAppImmigrationRoute
  AuthenticatedAppInsuranceRoute: typeof AuthenticatedAppInsuranceRoute
  AuthenticatedAppLocationRoute: typeof AuthenticatedAppLocationRoute
  AuthenticatedAppMessagesRoute: typeof AuthenticatedAppMessagesRouteWithChildren
  AuthenticatedAppNotificationsRoute: typeof AuthenticatedAppNotificationsRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedAppProvidersRoute: typeof AuthenticatedAppProvidersRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppStudentDiscountRoute: typeof AuthenticatedAppStudentDiscountRoute
  AuthenticatedAppUpgradeRoute: typeof AuthenticatedAppUpgradeRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAccountRoute: AuthenticatedAppAccountRoute,
  AuthenticatedAppAlertRoute: AuthenticatedAppAlertRoute,
  AuthenticatedAppAssistantRoute: AuthenticatedAppAssistantRoute,
  AuthenticatedAppBenefitsRoute: AuthenticatedAppBenefitsRoute,
  AuthenticatedAppBugsRoute: AuthenticatedAppBugsRoute,
  AuthenticatedAppCasesRoute: AuthenticatedAppCasesRouteWithChildren,
  AuthenticatedAppChecklistsRoute: AuthenticatedAppChecklistsRoute,
  AuthenticatedAppCommunityRoute: AuthenticatedAppCommunityRoute,
  AuthenticatedAppDocumentsRoute: AuthenticatedAppDocumentsRoute,
  AuthenticatedAppImmigrationRoute: AuthenticatedAppImmigrationRoute,
  AuthenticatedAppInsuranceRoute: AuthenticatedAppInsuranceRoute,
  AuthenticatedAppLocationRoute: AuthenticatedAppLocationRoute,
  AuthenticatedAppMessagesRoute: AuthenticatedAppMessagesRouteWithChildren,
  AuthenticatedAppNotificationsRoute: AuthenticatedAppNotificationsRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedAppProvidersRoute: AuthenticatedAppProvidersRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppStudentDiscountRoute: AuthenticatedAppStudentDiscountRoute,
  AuthenticatedAppUpgradeRoute: AuthenticatedAppUpgradeRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedExpertRouteChildren {
  AuthenticatedExpertAvailabilityRoute: typeof AuthenticatedExpertAvailabilityRoute
  AuthenticatedExpertCasesRoute: typeof AuthenticatedExpertCasesRoute
  AuthenticatedExpertInvoicesRoute: typeof AuthenticatedExpertInvoicesRoute
  AuthenticatedExpertPayoutsRoute: typeof AuthenticatedExpertPayoutsRoute
  AuthenticatedExpertProfileRoute: typeof AuthenticatedExpertProfileRoute
  AuthenticatedExpertQuotesRoute: typeof AuthenticatedExpertQuotesRoute
  AuthenticatedExpertIndexRoute: typeof AuthenticatedExpertIndexRoute
}

const AuthenticatedExpertRouteChildren: AuthenticatedExpertRouteChildren = {
  AuthenticatedExpertAvailabilityRoute: AuthenticatedExpertAvailabilityRoute,
  AuthenticatedExpertCasesRoute: AuthenticatedExpertCasesRoute,
  AuthenticatedExpertInvoicesRoute: AuthenticatedExpertInvoicesRoute,
  AuthenticatedExpertPayoutsRoute: AuthenticatedExpertPayoutsRoute,
  AuthenticatedExpertProfileRoute: AuthenticatedExpertProfileRoute,
  AuthenticatedExpertQuotesRoute: AuthenticatedExpertQuotesRoute,
  AuthenticatedExpertIndexRoute: AuthenticatedExpertIndexRoute,
}

const AuthenticatedExpertRouteWithChildren =
  AuthenticatedExpertRoute._addFileChildren(AuthenticatedExpertRouteChildren)

interface AuthenticatedPortalKnowledgeRouteChildren {
  AuthenticatedPortalKnowledgeSlugRoute: typeof AuthenticatedPortalKnowledgeSlugRoute
}

const AuthenticatedPortalKnowledgeRouteChildren: AuthenticatedPortalKnowledgeRouteChildren =
  {
    AuthenticatedPortalKnowledgeSlugRoute:
      AuthenticatedPortalKnowledgeSlugRoute,
  }

const AuthenticatedPortalKnowledgeRouteWithChildren =
  AuthenticatedPortalKnowledgeRoute._addFileChildren(
    AuthenticatedPortalKnowledgeRouteChildren,
  )

interface AuthenticatedPortalRouteChildren {
  AuthenticatedPortalAuditRoute: typeof AuthenticatedPortalAuditRoute
  AuthenticatedPortalBenefitsRoute: typeof AuthenticatedPortalBenefitsRoute
  AuthenticatedPortalCapacityRoute: typeof AuthenticatedPortalCapacityRoute
  AuthenticatedPortalDirectoryRoute: typeof AuthenticatedPortalDirectoryRoute
  AuthenticatedPortalEscrowRoute: typeof AuthenticatedPortalEscrowRoute
  AuthenticatedPortalExpertsRoute: typeof AuthenticatedPortalExpertsRoute
  AuthenticatedPortalFinancialsRoute: typeof AuthenticatedPortalFinancialsRoute
  AuthenticatedPortalFuneralRoute: typeof AuthenticatedPortalFuneralRoute
  AuthenticatedPortalFuneralCoverRoute: typeof AuthenticatedPortalFuneralCoverRoute
  AuthenticatedPortalImmigrationRoute: typeof AuthenticatedPortalImmigrationRoute
  AuthenticatedPortalInsuranceRoute: typeof AuthenticatedPortalInsuranceRoute
  AuthenticatedPortalKnowledgeRoute: typeof AuthenticatedPortalKnowledgeRouteWithChildren
  AuthenticatedPortalLeadsRoute: typeof AuthenticatedPortalLeadsRoute
  AuthenticatedPortalMedicalRoute: typeof AuthenticatedPortalMedicalRoute
  AuthenticatedPortalNewArrivalsRoute: typeof AuthenticatedPortalNewArrivalsRoute
  AuthenticatedPortalReferralsRoute: typeof AuthenticatedPortalReferralsRoute
  AuthenticatedPortalStudentsRoute: typeof AuthenticatedPortalStudentsRoute
  AuthenticatedPortalTaxRoute: typeof AuthenticatedPortalTaxRoute
  AuthenticatedPortalIndexRoute: typeof AuthenticatedPortalIndexRoute
  AuthenticatedPortalAdminInviteRoute: typeof AuthenticatedPortalAdminInviteRoute
  AuthenticatedPortalAdminUsersRoute: typeof AuthenticatedPortalAdminUsersRoute
  AuthenticatedPortalGanttCaseIdRoute: typeof AuthenticatedPortalGanttCaseIdRoute
}

const AuthenticatedPortalRouteChildren: AuthenticatedPortalRouteChildren = {
  AuthenticatedPortalAuditRoute: AuthenticatedPortalAuditRoute,
  AuthenticatedPortalBenefitsRoute: AuthenticatedPortalBenefitsRoute,
  AuthenticatedPortalCapacityRoute: AuthenticatedPortalCapacityRoute,
  AuthenticatedPortalDirectoryRoute: AuthenticatedPortalDirectoryRoute,
  AuthenticatedPortalEscrowRoute: AuthenticatedPortalEscrowRoute,
  AuthenticatedPortalExpertsRoute: AuthenticatedPortalExpertsRoute,
  AuthenticatedPortalFinancialsRoute: AuthenticatedPortalFinancialsRoute,
  AuthenticatedPortalFuneralRoute: AuthenticatedPortalFuneralRoute,
  AuthenticatedPortalFuneralCoverRoute: AuthenticatedPortalFuneralCoverRoute,
  AuthenticatedPortalImmigrationRoute: AuthenticatedPortalImmigrationRoute,
  AuthenticatedPortalInsuranceRoute: AuthenticatedPortalInsuranceRoute,
  AuthenticatedPortalKnowledgeRoute:
    AuthenticatedPortalKnowledgeRouteWithChildren,
  AuthenticatedPortalLeadsRoute: AuthenticatedPortalLeadsRoute,
  AuthenticatedPortalMedicalRoute: AuthenticatedPortalMedicalRoute,
  AuthenticatedPortalNewArrivalsRoute: AuthenticatedPortalNewArrivalsRoute,
  AuthenticatedPortalReferralsRoute: AuthenticatedPortalReferralsRoute,
  AuthenticatedPortalStudentsRoute: AuthenticatedPortalStudentsRoute,
  AuthenticatedPortalTaxRoute: AuthenticatedPortalTaxRoute,
  AuthenticatedPortalIndexRoute: AuthenticatedPortalIndexRoute,
  AuthenticatedPortalAdminInviteRoute: AuthenticatedPortalAdminInviteRoute,
  AuthenticatedPortalAdminUsersRoute: AuthenticatedPortalAdminUsersRoute,
  AuthenticatedPortalGanttCaseIdRoute: AuthenticatedPortalGanttCaseIdRoute,
}

const AuthenticatedPortalRouteWithChildren =
  AuthenticatedPortalRoute._addFileChildren(AuthenticatedPortalRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgentRoute: typeof AuthenticatedAgentRouteWithChildren
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedExpertRoute: typeof AuthenticatedExpertRouteWithChildren
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgentRoute: AuthenticatedAgentRouteWithChildren,
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedExpertRoute: AuthenticatedExpertRouteWithChildren,
  AuthenticatedPortalRoute: AuthenticatedPortalRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface DirectoryRouteChildren {
  DirectoryListYourBusinessRoute: typeof DirectoryListYourBusinessRoute
}

const DirectoryRouteChildren: DirectoryRouteChildren = {
  DirectoryListYourBusinessRoute: DirectoryListYourBusinessRoute,
}

const DirectoryRouteWithChildren = DirectoryRoute._addFileChildren(
  DirectoryRouteChildren,
)

interface GroupCoverRouteChildren {
  GroupCoverFiduciaryClauseRoute: typeof GroupCoverFiduciaryClauseRoute
}

const GroupCoverRouteChildren: GroupCoverRouteChildren = {
  GroupCoverFiduciaryClauseRoute: GroupCoverFiduciaryClauseRoute,
}

const GroupCoverRouteWithChildren = GroupCoverRoute._addFileChildren(
  GroupCoverRouteChildren,
)

interface LegalRouteChildren {
  LegalComplaintsRoute: typeof LegalComplaintsRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalImpressumRoute: typeof LegalImpressumRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
}

const LegalRouteChildren: LegalRouteChildren = {
  LegalComplaintsRoute: LegalComplaintsRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalImpressumRoute: LegalImpressumRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
}

const LegalRouteWithChildren = LegalRoute._addFileChildren(LegalRouteChildren)

interface PartnersRouteChildren {
  PartnersInsurersRoute: typeof PartnersInsurersRoute
}

const PartnersRouteChildren: PartnersRouteChildren = {
  PartnersInsurersRoute: PartnersInsurersRoute,
}

const PartnersRouteWithChildren = PartnersRoute._addFileChildren(
  PartnersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BereavementRoute: BereavementRoute,
  BereavementCoverRoute: BereavementCoverRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  DirectoryRoute: DirectoryRouteWithChildren,
  ForProvidersRoute: ForProvidersRoute,
  GroupCoverRoute: GroupCoverRouteWithChildren,
  HowItWorksRoute: HowItWorksRoute,
  InsuranceRoute: InsuranceRoute,
  IntegrationCoursesRoute: IntegrationCoursesRoute,
  LeavingGermanyRoute: LeavingGermanyRoute,
  LegalRoute: LegalRouteWithChildren,
  OfflineRoute: OfflineRoute,
  PartnersRoute: PartnersRouteWithChildren,
  PartnershipsRoute: PartnershipsRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudentsRoute: StudentsRoute,
  TaxRoute: TaxRoute,
  TrustRoute: TrustRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  ExpertInviteTokenRoute: ExpertInviteTokenRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
