/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ForProvidersRouteImport } from './routes/for-providers'
import { Route as DirectoryRouteImport } from './routes/directory'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BereavementCoverRouteImport } from './routes/bereavement-cover'
import { Route as BereavementRouteImport } from './routes/bereavement'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PartnersInsurersRouteImport } from './routes/partners.insurers'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalImpressumRouteImport } from './routes/legal.impressum'
import { Route as LegalCookiesRouteImport } from './routes/legal.cookies'
import { Route as LegalComplaintsRouteImport } from './routes/legal.complaints'
import { Route as DirectoryListYourBusinessRouteImport } from './routes/directory.list-your-business'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedPortalIndexRouteImport } from './routes/_authenticated/portal.index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedPortalLeadsRouteImport } from './routes/_authenticated/portal.leads'
import { Route as AuthenticatedPortalKnowledgeRouteImport } from './routes/_authenticated/portal.knowledge'
import { Route as AuthenticatedPortalFuneralRouteImport } from './routes/_authenticated/portal.funeral'
import { Route as AuthenticatedPortalExpertsRouteImport } from './routes/_authenticated/portal.experts'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as AuthenticatedAppProvidersRouteImport } from './routes/_authenticated/app.providers'
import { Route as AuthenticatedAppDocumentsRouteImport } from './routes/_authenticated/app.documents'
import { Route as AuthenticatedAppCommunityRouteImport } from './routes/_authenticated/app.community'
import { Route as AuthenticatedAppChecklistsRouteImport } from './routes/_authenticated/app.checklists'
import { Route as AuthenticatedAppCasesRouteImport } from './routes/_authenticated/app.cases'
import { Route as AuthenticatedAppBugsRouteImport } from './routes/_authenticated/app.bugs'
import { Route as AuthenticatedAppBenefitsRouteImport } from './routes/_authenticated/app.benefits'
import { Route as AuthenticatedAppAssistantRouteImport } from './routes/_authenticated/app.assistant'
import { Route as AuthenticatedPortalKnowledgeSlugRouteImport } from './routes/_authenticated/portal.knowledge.$slug'
import { Route as AuthenticatedPortalAdminUsersRouteImport } from './routes/_authenticated/portal.admin.users'
import { Route as AuthenticatedPortalAdminInviteRouteImport } from './routes/_authenticated/portal.admin.invite'
import { Route as AuthenticatedAppCasesNewRouteImport } from './routes/_authenticated/app.cases.new'
import { Route as AuthenticatedAppCasesCaseIdRouteImport } from './routes/_authenticated/app.cases.$caseId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ForProvidersRoute = ForProvidersRouteImport.update({
  id: '/for-providers',
  path: '/for-providers',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BereavementCoverRoute = BereavementCoverRouteImport.update({
  id: '/bereavement-cover',
  path: '/bereavement-cover',
  getParentRoute: () => rootRouteImport,
} as any)
const BereavementRoute = BereavementRouteImport.update({
  id: '/bereavement',
  path: '/bereavement',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersInsurersRoute = PartnersInsurersRouteImport.update({
  id: '/partners/insurers',
  path: '/partners/insurers',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LegalRoute,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LegalRoute,
} as any)
const LegalImpressumRoute = LegalImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => LegalRoute,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => LegalRoute,
} as any)
const LegalComplaintsRoute = LegalComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => LegalRoute,
} as any)
const DirectoryListYourBusinessRoute =
  DirectoryListYourBusinessRouteImport.update({
    id: '/list-your-business',
    path: '/list-your-business',
    getParentRoute: () => DirectoryRoute,
  } as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalIndexRoute =
  AuthenticatedPortalIndexRouteImport.update({
    id: '/portal/',
    path: '/portal/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedPortalLeadsRoute =
  AuthenticatedPortalLeadsRouteImport.update({
    id: '/portal/leads',
    path: '/portal/leads',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalKnowledgeRoute =
  AuthenticatedPortalKnowledgeRouteImport.update({
    id: '/portal/knowledge',
    path: '/portal/knowledge',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalFuneralRoute =
  AuthenticatedPortalFuneralRouteImport.update({
    id: '/portal/funeral',
    path: '/portal/funeral',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalExpertsRoute =
  AuthenticatedPortalExpertsRouteImport.update({
    id: '/portal/experts',
    path: '/portal/experts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProvidersRoute =
  AuthenticatedAppProvidersRouteImport.update({
    id: '/providers',
    path: '/providers',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDocumentsRoute =
  AuthenticatedAppDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCommunityRoute =
  AuthenticatedAppCommunityRouteImport.update({
    id: '/community',
    path: '/community',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppChecklistsRoute =
  AuthenticatedAppChecklistsRouteImport.update({
    id: '/checklists',
    path: '/checklists',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCasesRoute = AuthenticatedAppCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppBugsRoute = AuthenticatedAppBugsRouteImport.update({
  id: '/bugs',
  path: '/bugs',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppBenefitsRoute =
  AuthenticatedAppBenefitsRouteImport.update({
    id: '/benefits',
    path: '/benefits',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAssistantRoute =
  AuthenticatedAppAssistantRouteImport.update({
    id: '/assistant',
    path: '/assistant',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedPortalKnowledgeSlugRoute =
  AuthenticatedPortalKnowledgeSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedPortalKnowledgeRoute,
  } as any)
const AuthenticatedPortalAdminUsersRoute =
  AuthenticatedPortalAdminUsersRouteImport.update({
    id: '/portal/admin/users',
    path: '/portal/admin/users',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalAdminInviteRoute =
  AuthenticatedPortalAdminInviteRouteImport.update({
    id: '/portal/admin/invite',
    path: '/portal/admin/invite',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppCasesNewRoute =
  AuthenticatedAppCasesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAppCasesRoute,
  } as any)
const AuthenticatedAppCasesCaseIdRoute =
  AuthenticatedAppCasesCaseIdRouteImport.update({
    id: '/$caseId',
    path: '/$caseId',
    getParentRoute: () => AuthenticatedAppCasesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bereavement': typeof BereavementRoute
  '/bereavement-cover': typeof BereavementCoverRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/directory': typeof DirectoryRouteWithChildren
  '/for-providers': typeof ForProvidersRoute
  '/how-it-works': typeof HowItWorksRoute
  '/legal': typeof LegalRouteWithChildren
  '/pricing': typeof PricingRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/directory/list-your-business': typeof DirectoryListYourBusinessRoute
  '/legal/complaints': typeof LegalComplaintsRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/impressum': typeof LegalImpressumRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/partners/insurers': typeof PartnersInsurersRoute
  '/app/assistant': typeof AuthenticatedAppAssistantRoute
  '/app/benefits': typeof AuthenticatedAppBenefitsRoute
  '/app/bugs': typeof AuthenticatedAppBugsRoute
  '/app/cases': typeof AuthenticatedAppCasesRouteWithChildren
  '/app/checklists': typeof AuthenticatedAppChecklistsRoute
  '/app/community': typeof AuthenticatedAppCommunityRoute
  '/app/documents': typeof AuthenticatedAppDocumentsRoute
  '/app/providers': typeof AuthenticatedAppProvidersRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/portal/experts': typeof AuthenticatedPortalExpertsRoute
  '/portal/funeral': typeof AuthenticatedPortalFuneralRoute
  '/portal/knowledge': typeof AuthenticatedPortalKnowledgeRouteWithChildren
  '/portal/leads': typeof AuthenticatedPortalLeadsRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/portal/': typeof AuthenticatedPortalIndexRoute
  '/app/cases/$caseId': typeof AuthenticatedAppCasesCaseIdRoute
  '/app/cases/new': typeof AuthenticatedAppCasesNewRoute
  '/portal/admin/invite': typeof AuthenticatedPortalAdminInviteRoute
  '/portal/admin/users': typeof AuthenticatedPortalAdminUsersRoute
  '/portal/knowledge/$slug': typeof AuthenticatedPortalKnowledgeSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bereavement': typeof BereavementRoute
  '/bereavement-cover': typeof BereavementCoverRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/directory': typeof DirectoryRouteWithChildren
  '/for-providers': typeof ForProvidersRoute
  '/how-it-works': typeof HowItWorksRoute
  '/legal': typeof LegalRouteWithChildren
  '/pricing': typeof PricingRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/directory/list-your-business': typeof DirectoryListYourBusinessRoute
  '/legal/complaints': typeof LegalComplaintsRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/impressum': typeof LegalImpressumRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/partners/insurers': typeof PartnersInsurersRoute
  '/app/assistant': typeof AuthenticatedAppAssistantRoute
  '/app/benefits': typeof AuthenticatedAppBenefitsRoute
  '/app/bugs': typeof AuthenticatedAppBugsRoute
  '/app/cases': typeof AuthenticatedAppCasesRouteWithChildren
  '/app/checklists': typeof AuthenticatedAppChecklistsRoute
  '/app/community': typeof AuthenticatedAppCommunityRoute
  '/app/documents': typeof AuthenticatedAppDocumentsRoute
  '/app/providers': typeof AuthenticatedAppProvidersRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/portal/experts': typeof AuthenticatedPortalExpertsRoute
  '/portal/funeral': typeof AuthenticatedPortalFuneralRoute
  '/portal/knowledge': typeof AuthenticatedPortalKnowledgeRouteWithChildren
  '/portal/leads': typeof AuthenticatedPortalLeadsRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/portal': typeof AuthenticatedPortalIndexRoute
  '/app/cases/$caseId': typeof AuthenticatedAppCasesCaseIdRoute
  '/app/cases/new': typeof AuthenticatedAppCasesNewRoute
  '/portal/admin/invite': typeof AuthenticatedPortalAdminInviteRoute
  '/portal/admin/users': typeof AuthenticatedPortalAdminUsersRoute
  '/portal/knowledge/$slug': typeof AuthenticatedPortalKnowledgeSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/bereavement': typeof BereavementRoute
  '/bereavement-cover': typeof BereavementCoverRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/directory': typeof DirectoryRouteWithChildren
  '/for-providers': typeof ForProvidersRoute
  '/how-it-works': typeof HowItWorksRoute
  '/legal': typeof LegalRouteWithChildren
  '/pricing': typeof PricingRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/directory/list-your-business': typeof DirectoryListYourBusinessRoute
  '/legal/complaints': typeof LegalComplaintsRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/impressum': typeof LegalImpressumRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/partners/insurers': typeof PartnersInsurersRoute
  '/_authenticated/app/assistant': typeof AuthenticatedAppAssistantRoute
  '/_authenticated/app/benefits': typeof AuthenticatedAppBenefitsRoute
  '/_authenticated/app/bugs': typeof AuthenticatedAppBugsRoute
  '/_authenticated/app/cases': typeof AuthenticatedAppCasesRouteWithChildren
  '/_authenticated/app/checklists': typeof AuthenticatedAppChecklistsRoute
  '/_authenticated/app/community': typeof AuthenticatedAppCommunityRoute
  '/_authenticated/app/documents': typeof AuthenticatedAppDocumentsRoute
  '/_authenticated/app/providers': typeof AuthenticatedAppProvidersRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/portal/experts': typeof AuthenticatedPortalExpertsRoute
  '/_authenticated/portal/funeral': typeof AuthenticatedPortalFuneralRoute
  '/_authenticated/portal/knowledge': typeof AuthenticatedPortalKnowledgeRouteWithChildren
  '/_authenticated/portal/leads': typeof AuthenticatedPortalLeadsRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/portal/': typeof AuthenticatedPortalIndexRoute
  '/_authenticated/app/cases/$caseId': typeof AuthenticatedAppCasesCaseIdRoute
  '/_authenticated/app/cases/new': typeof AuthenticatedAppCasesNewRoute
  '/_authenticated/portal/admin/invite': typeof AuthenticatedPortalAdminInviteRoute
  '/_authenticated/portal/admin/users': typeof AuthenticatedPortalAdminUsersRoute
  '/_authenticated/portal/knowledge/$slug': typeof AuthenticatedPortalKnowledgeSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bereavement'
    | '/bereavement-cover'
    | '/blog'
    | '/contact'
    | '/directory'
    | '/for-providers'
    | '/how-it-works'
    | '/legal'
    | '/pricing'
    | '/services'
    | '/sitemap.xml'
    | '/app'
    | '/blog/$slug'
    | '/directory/list-your-business'
    | '/legal/complaints'
    | '/legal/cookies'
    | '/legal/impressum'
    | '/legal/privacy'
    | '/legal/terms'
    | '/partners/insurers'
    | '/app/assistant'
    | '/app/benefits'
    | '/app/bugs'
    | '/app/cases'
    | '/app/checklists'
    | '/app/community'
    | '/app/documents'
    | '/app/providers'
    | '/app/settings'
    | '/portal/experts'
    | '/portal/funeral'
    | '/portal/knowledge'
    | '/portal/leads'
    | '/app/'
    | '/portal/'
    | '/app/cases/$caseId'
    | '/app/cases/new'
    | '/portal/admin/invite'
    | '/portal/admin/users'
    | '/portal/knowledge/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bereavement'
    | '/bereavement-cover'
    | '/blog'
    | '/contact'
    | '/directory'
    | '/for-providers'
    | '/how-it-works'
    | '/legal'
    | '/pricing'
    | '/services'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/directory/list-your-business'
    | '/legal/complaints'
    | '/legal/cookies'
    | '/legal/impressum'
    | '/legal/privacy'
    | '/legal/terms'
    | '/partners/insurers'
    | '/app/assistant'
    | '/app/benefits'
    | '/app/bugs'
    | '/app/cases'
    | '/app/checklists'
    | '/app/community'
    | '/app/documents'
    | '/app/providers'
    | '/app/settings'
    | '/portal/experts'
    | '/portal/funeral'
    | '/portal/knowledge'
    | '/portal/leads'
    | '/app'
    | '/portal'
    | '/app/cases/$caseId'
    | '/app/cases/new'
    | '/portal/admin/invite'
    | '/portal/admin/users'
    | '/portal/knowledge/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/bereavement'
    | '/bereavement-cover'
    | '/blog'
    | '/contact'
    | '/directory'
    | '/for-providers'
    | '/how-it-works'
    | '/legal'
    | '/pricing'
    | '/services'
    | '/sitemap.xml'
    | '/_authenticated/app'
    | '/blog/$slug'
    | '/directory/list-your-business'
    | '/legal/complaints'
    | '/legal/cookies'
    | '/legal/impressum'
    | '/legal/privacy'
    | '/legal/terms'
    | '/partners/insurers'
    | '/_authenticated/app/assistant'
    | '/_authenticated/app/benefits'
    | '/_authenticated/app/bugs'
    | '/_authenticated/app/cases'
    | '/_authenticated/app/checklists'
    | '/_authenticated/app/community'
    | '/_authenticated/app/documents'
    | '/_authenticated/app/providers'
    | '/_authenticated/app/settings'
    | '/_authenticated/portal/experts'
    | '/_authenticated/portal/funeral'
    | '/_authenticated/portal/knowledge'
    | '/_authenticated/portal/leads'
    | '/_authenticated/app/'
    | '/_authenticated/portal/'
    | '/_authenticated/app/cases/$caseId'
    | '/_authenticated/app/cases/new'
    | '/_authenticated/portal/admin/invite'
    | '/_authenticated/portal/admin/users'
    | '/_authenticated/portal/knowledge/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BereavementRoute: typeof BereavementRoute
  BereavementCoverRoute: typeof BereavementCoverRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  DirectoryRoute: typeof DirectoryRouteWithChildren
  ForProvidersRoute: typeof ForProvidersRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LegalRoute: typeof LegalRouteWithChildren
  PricingRoute: typeof PricingRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  PartnersInsurersRoute: typeof PartnersInsurersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-providers': {
      id: '/for-providers'
      path: '/for-providers'
      fullPath: '/for-providers'
      preLoaderRoute: typeof ForProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bereavement-cover': {
      id: '/bereavement-cover'
      path: '/bereavement-cover'
      fullPath: '/bereavement-cover'
      preLoaderRoute: typeof BereavementCoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bereavement': {
      id: '/bereavement'
      path: '/bereavement'
      fullPath: '/bereavement'
      preLoaderRoute: typeof BereavementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners/insurers': {
      id: '/partners/insurers'
      path: '/partners/insurers'
      fullPath: '/partners/insurers'
      preLoaderRoute: typeof PartnersInsurersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/impressum': {
      id: '/legal/impressum'
      path: '/impressum'
      fullPath: '/legal/impressum'
      preLoaderRoute: typeof LegalImpressumRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/complaints': {
      id: '/legal/complaints'
      path: '/complaints'
      fullPath: '/legal/complaints'
      preLoaderRoute: typeof LegalComplaintsRouteImport
      parentRoute: typeof LegalRoute
    }
    '/directory/list-your-business': {
      id: '/directory/list-your-business'
      path: '/list-your-business'
      fullPath: '/directory/list-your-business'
      preLoaderRoute: typeof DirectoryListYourBusinessRouteImport
      parentRoute: typeof DirectoryRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/': {
      id: '/_authenticated/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof AuthenticatedPortalIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/portal/leads': {
      id: '/_authenticated/portal/leads'
      path: '/portal/leads'
      fullPath: '/portal/leads'
      preLoaderRoute: typeof AuthenticatedPortalLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/knowledge': {
      id: '/_authenticated/portal/knowledge'
      path: '/portal/knowledge'
      fullPath: '/portal/knowledge'
      preLoaderRoute: typeof AuthenticatedPortalKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/funeral': {
      id: '/_authenticated/portal/funeral'
      path: '/portal/funeral'
      fullPath: '/portal/funeral'
      preLoaderRoute: typeof AuthenticatedPortalFuneralRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/experts': {
      id: '/_authenticated/portal/experts'
      path: '/portal/experts'
      fullPath: '/portal/experts'
      preLoaderRoute: typeof AuthenticatedPortalExpertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/providers': {
      id: '/_authenticated/app/providers'
      path: '/providers'
      fullPath: '/app/providers'
      preLoaderRoute: typeof AuthenticatedAppProvidersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/documents': {
      id: '/_authenticated/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AuthenticatedAppDocumentsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/community': {
      id: '/_authenticated/app/community'
      path: '/community'
      fullPath: '/app/community'
      preLoaderRoute: typeof AuthenticatedAppCommunityRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/checklists': {
      id: '/_authenticated/app/checklists'
      path: '/checklists'
      fullPath: '/app/checklists'
      preLoaderRoute: typeof AuthenticatedAppChecklistsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/cases': {
      id: '/_authenticated/app/cases'
      path: '/cases'
      fullPath: '/app/cases'
      preLoaderRoute: typeof AuthenticatedAppCasesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/bugs': {
      id: '/_authenticated/app/bugs'
      path: '/bugs'
      fullPath: '/app/bugs'
      preLoaderRoute: typeof AuthenticatedAppBugsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/benefits': {
      id: '/_authenticated/app/benefits'
      path: '/benefits'
      fullPath: '/app/benefits'
      preLoaderRoute: typeof AuthenticatedAppBenefitsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/assistant': {
      id: '/_authenticated/app/assistant'
      path: '/assistant'
      fullPath: '/app/assistant'
      preLoaderRoute: typeof AuthenticatedAppAssistantRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/portal/knowledge/$slug': {
      id: '/_authenticated/portal/knowledge/$slug'
      path: '/$slug'
      fullPath: '/portal/knowledge/$slug'
      preLoaderRoute: typeof AuthenticatedPortalKnowledgeSlugRouteImport
      parentRoute: typeof AuthenticatedPortalKnowledgeRoute
    }
    '/_authenticated/portal/admin/users': {
      id: '/_authenticated/portal/admin/users'
      path: '/portal/admin/users'
      fullPath: '/portal/admin/users'
      preLoaderRoute: typeof AuthenticatedPortalAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/admin/invite': {
      id: '/_authenticated/portal/admin/invite'
      path: '/portal/admin/invite'
      fullPath: '/portal/admin/invite'
      preLoaderRoute: typeof AuthenticatedPortalAdminInviteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/cases/new': {
      id: '/_authenticated/app/cases/new'
      path: '/new'
      fullPath: '/app/cases/new'
      preLoaderRoute: typeof AuthenticatedAppCasesNewRouteImport
      parentRoute: typeof AuthenticatedAppCasesRoute
    }
    '/_authenticated/app/cases/$caseId': {
      id: '/_authenticated/app/cases/$caseId'
      path: '/$caseId'
      fullPath: '/app/cases/$caseId'
      preLoaderRoute: typeof AuthenticatedAppCasesCaseIdRouteImport
      parentRoute: typeof AuthenticatedAppCasesRoute
    }
  }
}

interface AuthenticatedAppCasesRouteChildren {
  AuthenticatedAppCasesCaseIdRoute: typeof AuthenticatedAppCasesCaseIdRoute
  AuthenticatedAppCasesNewRoute: typeof AuthenticatedAppCasesNewRoute
}

const AuthenticatedAppCasesRouteChildren: AuthenticatedAppCasesRouteChildren = {
  AuthenticatedAppCasesCaseIdRoute: AuthenticatedAppCasesCaseIdRoute,
  AuthenticatedAppCasesNewRoute: AuthenticatedAppCasesNewRoute,
}

const AuthenticatedAppCasesRouteWithChildren =
  AuthenticatedAppCasesRoute._addFileChildren(
    AuthenticatedAppCasesRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAssistantRoute: typeof AuthenticatedAppAssistantRoute
  AuthenticatedAppBenefitsRoute: typeof AuthenticatedAppBenefitsRoute
  AuthenticatedAppBugsRoute: typeof AuthenticatedAppBugsRoute
  AuthenticatedAppCasesRoute: typeof AuthenticatedAppCasesRouteWithChildren
  AuthenticatedAppChecklistsRoute: typeof AuthenticatedAppChecklistsRoute
  AuthenticatedAppCommunityRoute: typeof AuthenticatedAppCommunityRoute
  AuthenticatedAppDocumentsRoute: typeof AuthenticatedAppDocumentsRoute
  AuthenticatedAppProvidersRoute: typeof AuthenticatedAppProvidersRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAssistantRoute: AuthenticatedAppAssistantRoute,
  AuthenticatedAppBenefitsRoute: AuthenticatedAppBenefitsRoute,
  AuthenticatedAppBugsRoute: AuthenticatedAppBugsRoute,
  AuthenticatedAppCasesRoute: AuthenticatedAppCasesRouteWithChildren,
  AuthenticatedAppChecklistsRoute: AuthenticatedAppChecklistsRoute,
  AuthenticatedAppCommunityRoute: AuthenticatedAppCommunityRoute,
  AuthenticatedAppDocumentsRoute: AuthenticatedAppDocumentsRoute,
  AuthenticatedAppProvidersRoute: AuthenticatedAppProvidersRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedPortalKnowledgeRouteChildren {
  AuthenticatedPortalKnowledgeSlugRoute: typeof AuthenticatedPortalKnowledgeSlugRoute
}

const AuthenticatedPortalKnowledgeRouteChildren: AuthenticatedPortalKnowledgeRouteChildren =
  {
    AuthenticatedPortalKnowledgeSlugRoute:
      AuthenticatedPortalKnowledgeSlugRoute,
  }

const AuthenticatedPortalKnowledgeRouteWithChildren =
  AuthenticatedPortalKnowledgeRoute._addFileChildren(
    AuthenticatedPortalKnowledgeRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedPortalExpertsRoute: typeof AuthenticatedPortalExpertsRoute
  AuthenticatedPortalFuneralRoute: typeof AuthenticatedPortalFuneralRoute
  AuthenticatedPortalKnowledgeRoute: typeof AuthenticatedPortalKnowledgeRouteWithChildren
  AuthenticatedPortalLeadsRoute: typeof AuthenticatedPortalLeadsRoute
  AuthenticatedPortalIndexRoute: typeof AuthenticatedPortalIndexRoute
  AuthenticatedPortalAdminInviteRoute: typeof AuthenticatedPortalAdminInviteRoute
  AuthenticatedPortalAdminUsersRoute: typeof AuthenticatedPortalAdminUsersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedPortalExpertsRoute: AuthenticatedPortalExpertsRoute,
  AuthenticatedPortalFuneralRoute: AuthenticatedPortalFuneralRoute,
  AuthenticatedPortalKnowledgeRoute:
    AuthenticatedPortalKnowledgeRouteWithChildren,
  AuthenticatedPortalLeadsRoute: AuthenticatedPortalLeadsRoute,
  AuthenticatedPortalIndexRoute: AuthenticatedPortalIndexRoute,
  AuthenticatedPortalAdminInviteRoute: AuthenticatedPortalAdminInviteRoute,
  AuthenticatedPortalAdminUsersRoute: AuthenticatedPortalAdminUsersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface DirectoryRouteChildren {
  DirectoryListYourBusinessRoute: typeof DirectoryListYourBusinessRoute
}

const DirectoryRouteChildren: DirectoryRouteChildren = {
  DirectoryListYourBusinessRoute: DirectoryListYourBusinessRoute,
}

const DirectoryRouteWithChildren = DirectoryRoute._addFileChildren(
  DirectoryRouteChildren,
)

interface LegalRouteChildren {
  LegalComplaintsRoute: typeof LegalComplaintsRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalImpressumRoute: typeof LegalImpressumRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
}

const LegalRouteChildren: LegalRouteChildren = {
  LegalComplaintsRoute: LegalComplaintsRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalImpressumRoute: LegalImpressumRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
}

const LegalRouteWithChildren = LegalRoute._addFileChildren(LegalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BereavementRoute: BereavementRoute,
  BereavementCoverRoute: BereavementCoverRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  DirectoryRoute: DirectoryRouteWithChildren,
  ForProvidersRoute: ForProvidersRoute,
  HowItWorksRoute: HowItWorksRoute,
  LegalRoute: LegalRouteWithChildren,
  PricingRoute: PricingRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  PartnersInsurersRoute: PartnersInsurersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
