CREATE TABLE public.benefits_catalogue (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  sort_order integer NOT NULL DEFAULT 0,
  name text NOT NULL,
  german text NOT NULL,
  summary text NOT NULL,
  monthly text,
  category text NOT NULL,
  authority text NOT NULL,
  eligible_if text[] NOT NULL DEFAULT '{}',
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  apply_url text,
  notes text,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

GRANT SELECT ON public.benefits_catalogue TO anon, authenticated;
GRANT ALL ON public.benefits_catalogue TO service_role;

ALTER TABLE public.benefits_catalogue ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Benefits catalogue is public read" ON public.benefits_catalogue
  FOR SELECT TO anon, authenticated USING (active = true);

CREATE POLICY "Admins manage benefits catalogue" ON public.benefits_catalogue
  FOR ALL TO authenticated USING (public.has_role(auth.uid(),'admin'))
  WITH CHECK (public.has_role(auth.uid(),'admin'));

CREATE TRIGGER update_benefits_catalogue_updated_at
  BEFORE UPDATE ON public.benefits_catalogue
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

INSERT INTO public.benefits_catalogue
  (key, sort_order, name, german, summary, monthly, category, authority, eligible_if, payload, apply_url, notes)
VALUES
('kindergeld', 0, 'Child Benefit', 'Kindergeld', 'Monthly payment for every child under 18 (up to 25 if in education/training).', '€255 / child', 'family', 'Familienkasse (Bundesagentur für Arbeit)', ARRAY['Registered address (Anmeldung) in Germany','Legal residence permit or EU citizenship','Child lives in your household or in the EU/EEA']::text[], '{"forms":[{"code":"KG 1","title":"Antrag auf Kindergeld","url":"https://www.arbeitsagentur.de/datei/kg1-kindergeldantrag_ba013008.pdf"},{"code":"KG 1-Anlage Kind","title":"Anlage Kind (one per child)"},{"code":"KG 51","title":"Anlage Ausland (if child abroad)"}],"documents":["Valid passport or national ID","Residence permit (Aufenthaltstitel) if non-EU","Anmeldebestätigung (address registration)","Tax ID (Steuer-Identifikationsnummer)","Child''s birth certificate (translated & apostilled if foreign)","Child''s Steuer-ID","Custody proof if separated"],"proofs":["School / university / apprenticeship certificate for children 18–25","Marriage certificate if claiming for stepchildren"]}'::jsonb, 'https://www.arbeitsagentur.de/familie-und-kinder/kindergeld-antrag', 'Apply within 6 months of birth for full back-payment.'),
('elterngeld', 1, 'Parental Allowance', 'Elterngeld / ElterngeldPlus', 'Income replacement (65–67%) for parents who reduce working hours after birth.', '€300–€1,800', 'family', 'Elterngeldstelle (Bezirksamt / Jugendamt)', ARRAY['Baby under 14 months (Basiselterngeld)','Working ≤ 32h/week during the claim','Legal residence with permit allowing work']::text[], '{"forms":[{"code":"Elterngeld-Antrag","title":"Antrag auf Elterngeld (state-specific PDF)"},{"code":"Anlage N","title":"Nachweis Einkommen aus nichtselbständiger Arbeit"},{"code":"Anlage S","title":"Nachweis Einkommen aus selbständiger Arbeit"}],"documents":["Valid passport or national ID","Residence permit (Aufenthaltstitel) if non-EU","Anmeldebestätigung (address registration)","Tax ID (Steuer-Identifikationsnummer)","Original birth certificate with ''Verwendungszweck: Elterngeld''","Health insurance confirmation","Employer confirmation of parental leave (Bescheinigung Elternzeit)"],"proofs":["12 months of payslips before birth","Tax assessment (Steuerbescheid) for self-employed","Mutterschaftsgeld notice from Krankenkasse"]}'::jsonb, 'https://www.elterngeld-digital.de', 'Apply within the first 3 months to avoid losing months of payment.'),
('kinderzuschlag', 2, 'Child Supplement', 'Kinderzuschlag (KiZ)', 'Up to €297 per child for low-income working parents who don''t qualify for Bürgergeld.', 'up to €297 / child', 'family', 'Familienkasse', ARRAY['Parent(s) earn at least €900 (couples) or €600 (single) gross/month','Household income too low to cover children''s needs','Receives or is eligible for Kindergeld']::text[], '{"forms":[{"code":"KiZ 1","title":"Hauptantrag Kinderzuschlag","url":"https://www.arbeitsagentur.de/datei/kiz1_ba014396.pdf"},{"code":"KiZ-Anlage Kind","title":"Anlage Kind"},{"code":"KiZ-Anlage Einkommen","title":"Anlage Einkommen (per adult)"}],"documents":["Valid passport or national ID","Residence permit (Aufenthaltstitel) if non-EU","Anmeldebestätigung (address registration)","Tax ID (Steuer-Identifikationsnummer)","Rental contract + last utility bill","Health insurance card"],"proofs":["Last 3 payslips (Lohn-/Gehaltsabrechnung)","Employment contract or self-employment income statement","Bank statements (last 3 months)","Rent + heating cost proof","Child-care cost proof"]}'::jsonb, 'https://www.arbeitsagentur.de/familie-und-kinder/kinderzuschlag-antrag', NULL),
('unterhaltsvorschuss', 3, 'Advance Maintenance Payment', 'Unterhaltsvorschuss', 'State advances child maintenance when the other parent does not pay.', '€230–€395 / child', 'family', 'Jugendamt / Unterhaltsvorschusskasse', ARRAY['Child lives with a single parent','Other parent pays no or reduced maintenance','Child under 18']::text[], '{"forms":[{"code":"UVG","title":"Antrag Unterhaltsvorschuss (Kommune)"}],"documents":["Valid passport or national ID","Residence permit (Aufenthaltstitel) if non-EU","Anmeldebestätigung (address registration)","Tax ID (Steuer-Identifikationsnummer)","Child''s birth certificate","Custody decision or proof of separation","Any existing maintenance title (Unterhaltstitel)"],"proofs":["Bank statements showing missing payments","Correspondence with the other parent"]}'::jsonb, NULL, NULL),
('mutterschaftsgeld', 4, 'Maternity Pay', 'Mutterschaftsgeld', 'Full net income replacement 6 weeks before and 8 weeks after birth (12 for multiples).', 'up to €13 / day + employer top-up', 'family', 'Statutory Krankenkasse (GKV)', ARRAY['Statutorily insured with sick-pay entitlement','Pregnant with medical Mutterpass','In employment or Elterngeld-relevant income']::text[], '{"forms":[{"code":"Muschg","title":"Antrag Mutterschaftsgeld der Krankenkasse"}],"documents":["Valid passport or national ID","Residence permit (Aufenthaltstitel) if non-EU","Anmeldebestätigung (address registration)","Tax ID (Steuer-Identifikationsnummer)","Mutterpass","Employer confirmation"],"proofs":["Doctor''s certificate with expected delivery date"]}'::jsonb, NULL, NULL),
('entlastungsbetrag_ae', 5, 'Single-Parent Tax Relief', 'Entlastungsbetrag für Alleinerziehende', '€4,260 base + €240 per additional child, deducted from taxable income.', '≈ €80–€150 / month tax saving', 'tax', 'Finanzamt (Steuerklasse II)', ARRAY['Single parent living alone with at least one child','Child registered at your address and eligible for Kindergeld']::text[], '{"forms":[{"code":"Anlage Kind","title":"Anlage Kind zur Einkommensteuererklärung"},{"code":"Steuerklassenwechsel","title":"Antrag Wechsel Steuerklasse II"}],"documents":["Valid passport or national ID","Residence permit (Aufenthaltstitel) if non-EU","Anmeldebestätigung (address registration)","Tax ID (Steuer-Identifikationsnummer)","Meldebescheinigung showing single-adult household"],"proofs":["Kindergeld notice","School enrolment for the child"]}'::jsonb, NULL, NULL),
('wohngeld', 6, 'Housing Benefit', 'Wohngeld', 'Rent subsidy for low-income working households not on Bürgergeld.', '€100–€800', 'housing', 'Wohngeldbehörde (Bezirksamt)', ARRAY['Legal residence & registered rental contract','Household income below regional cap','Not receiving Bürgergeld / Sozialhilfe / BAföG']::text[], '{"forms":[{"code":"Wohngeldantrag","title":"Antrag auf Wohngeld (Mietzuschuss)"},{"code":"Vermieterbescheinigung","title":"Bescheinigung des Vermieters"},{"code":"Verdienstbescheinigung","title":"Verdienstbescheinigung Arbeitgeber"}],"documents":["Valid passport or national ID","Residence permit (Aufenthaltstitel) if non-EU","Anmeldebestätigung (address registration)","Tax ID (Steuer-Identifikationsnummer)","Rental contract","Utility & heating bills"],"proofs":["Last 3 payslips (Lohn-/Gehaltsabrechnung)","Employment contract or self-employment income statement","Bank statements (last 3 months)","Health insurance & pension contribution proof"]}'::jsonb, NULL, NULL),
('wbs', 7, 'Social Housing Certificate', 'Wohnberechtigungsschein (WBS)', 'Entitles you to apply for state-subsidised (Sozialwohnung) apartments.', NULL, 'housing', 'Wohnungsamt (Bezirksamt)', ARRAY['Household income under state-set income limits','Legal residence in Germany for at least 12 months']::text[], '{"forms":[{"code":"WBS-Antrag","title":"Antrag auf Wohnberechtigungsschein"}],"documents":["Valid passport or national ID","Residence permit (Aufenthaltstitel) if non-EU","Anmeldebestätigung (address registration)","Tax ID (Steuer-Identifikationsnummer)","Rental contract or written housing search proof"],"proofs":["Last 3 payslips (Lohn-/Gehaltsabrechnung)","Employment contract or self-employment income statement","Bank statements (last 3 months)","Tax assessment (Steuerbescheid) if available"]}'::jsonb, NULL, NULL),
('heizkostenzuschuss', 8, 'Heating Cost Subsidy', 'Heizkostenzuschuss', 'One-off support toward heating bills for Wohngeld / BAföG / Ausbildungsbeihilfe recipients.', NULL, 'housing', 'Wohngeldbehörde', ARRAY['Currently receiving Wohngeld, BAföG or BAB in the reference period']::text[], '{"forms":[{"code":"Automatisch","title":"Paid automatically — no separate application"}],"documents":["Copy of Wohngeld / BAföG / BAB decision"],"proofs":["Heating bill copy if requested by authority"]}'::jsonb, NULL, NULL),
('buergergeld', 9, 'Basic Income Support', 'Bürgergeld (SGB II)', 'Minimum living support including rent, heating and health insurance for job-seekers.', '€563 / adult + rent + heating', 'income', 'Jobcenter', ARRAY['Legal residence with access to labour market','Able to work at least 3 h / day','Household assets below Schonvermögen threshold']::text[], '{"forms":[{"code":"HA","title":"Hauptantrag Bürgergeld","url":"https://www.arbeitsagentur.de/datei/ba015207.pdf"},{"code":"WEP","title":"Anlage WEP (weitere Personen im Haushalt)"},{"code":"KDU","title":"Anlage KDU (Kosten der Unterkunft)"},{"code":"EK","title":"Anlage EK (Einkommen)"},{"code":"VM","title":"Anlage VM (Vermögen)"}],"documents":["Valid passport or national ID","Residence permit (Aufenthaltstitel) if non-EU","Anmeldebestätigung (address registration)","Tax ID (Steuer-Identifikationsnummer)","Rental contract + latest heating statement","Bank statements for all household accounts (last 3 months)"],"proofs":["Last 3 payslips (Lohn-/Gehaltsabrechnung)","Employment contract or self-employment income statement","Bank statements (last 3 months)","Job-search evidence / Arbeitsuchendmeldung","Health insurance card or letter"]}'::jsonb, NULL, NULL),
('sozialhilfe', 10, 'Social Assistance (SGB XII)', 'Sozialhilfe / Hilfe zum Lebensunterhalt', 'Livelihood support for people temporarily unable to work who don''t qualify for Bürgergeld.', '€563 / adult + rent', 'income', 'Sozialamt', ARRAY['Unable to work < 3 h/day for at least 6 months','Not entitled to Bürgergeld or pension','Assets below Schonvermögen']::text[], '{"forms":[{"code":"SGB XII Antrag","title":"Antrag auf Leistungen nach dem SGB XII"}],"documents":["Valid passport or national ID","Residence permit (Aufenthaltstitel) if non-EU","Anmeldebestätigung (address registration)","Tax ID (Steuer-Identifikationsnummer)","Rental contract","Bank statements 3 months"],"proofs":["Medical certificate on ability to work","Last 3 payslips (Lohn-/Gehaltsabrechnung)","Employment contract or self-employment income statement","Bank statements (last 3 months)","Pension / benefit decisions"]}'::jsonb, NULL, NULL),
('grundsicherung_alter_em', 11, 'Basic Security in Old Age / Reduced Earning Capacity', 'Grundsicherung im Alter und bei Erwerbsminderung', 'Minimum income for retirees or those with permanently reduced earning capacity.', '€563 / adult + rent + heating', 'income', 'Sozialamt (Grundsicherungsstelle)', ARRAY['At retirement age OR permanently unable to work','Pension or income below Grundsicherung need','Legal residence with settled status']::text[], '{"forms":[{"code":"GruSi","title":"Antrag Grundsicherung nach 4. Kapitel SGB XII"}],"documents":["Valid passport or national ID","Residence permit (Aufenthaltstitel) if non-EU","Anmeldebestätigung (address registration)","Tax ID (Steuer-Identifikationsnummer)","Pension decisions","Rental contract"],"proofs":["Rentenbescheid","Medical proof of Erwerbsminderung if under retirement age"]}'::jsonb, NULL, NULL),
('bafog', 12, 'Student Grant / Loan', 'BAföG', 'Study financing — 50 % grant, 50 % interest-free loan (max €992 / month).', 'up to €992', 'student', 'BAföG-Amt (Studentenwerk)', ARRAY['Enrolled at a recognised university or Fachschule','Under 45 at start of studies','Parental income below cap (or 5+ years of prior work in Germany)']::text[], '{"forms":[{"code":"Formblatt 1","title":"Hauptantrag BAföG"},{"code":"Formblatt 3","title":"Einkommensnachweis Eltern / Ehepartner"},{"code":"Formblatt 5","title":"Studien-/Ausbildungsnachweis"}],"documents":["Valid passport or national ID","Residence permit (Aufenthaltstitel) if non-EU","Anmeldebestätigung (address registration)","Tax ID (Steuer-Identifikationsnummer)","Immatrikulationsbescheinigung","Health insurance proof"],"proofs":["Parents'' tax assessments (Steuerbescheid) last 2 years","Rental contract if living alone"]}'::jsonb, 'https://www.bafoeg-digital.de', NULL),
('aufstiegs_bafog', 13, 'Career Advancement Loan', 'Aufstiegs-BAföG (Meister-BAföG)', 'Support for professional upskilling (Meister, Techniker, Fachwirt).', 'up to €963 living + course fees', 'student', 'BAföG-Amt / Landesamt', ARRAY['Preparing for a recognised advancement qualification','Course of at least 400 hours or 200 hours (part-time)']::text[], '{"forms":[{"code":"AFBG","title":"Antrag Aufstiegs-BAföG"}],"documents":["Valid passport or national ID","Residence permit (Aufenthaltstitel) if non-EU","Anmeldebestätigung (address registration)","Tax ID (Steuer-Identifikationsnummer)","Course contract","Existing vocational qualification"],"proofs":["Curriculum / hour breakdown","Employer confirmation if part-time"]}'::jsonb, NULL, NULL),
('bildungspaket', 14, 'Education & Participation Package', 'Bildungs- und Teilhabepaket (BuT)', 'School supplies, lunches, tutoring and club fees for children in low-income households.', '€15 club + €195 / year school supplies + lunches', 'family', 'Jobcenter / Sozialamt / Bildungsträger', ARRAY['Household receives Bürgergeld, Sozialhilfe, Wohngeld, Kinderzuschlag or Asylbewerberleistungen','Child under 25 in school, kindergarten or Kita']::text[], '{"forms":[{"code":"BuT-Antrag","title":"Antrag Bildung und Teilhabe (Kommune)"}],"documents":["Valid passport or national ID","Residence permit (Aufenthaltstitel) if non-EU","Anmeldebestätigung (address registration)","Tax ID (Steuer-Identifikationsnummer)","Current benefit decision","School / club confirmation"],"proofs":["Invoice / offer from tutor, club or trip organiser"]}'::jsonb, NULL, NULL),
('rente', 15, 'State Pension', 'Gesetzliche Altersrente', 'Retirement pension based on contribution years and average earnings.', NULL, 'pension', 'Deutsche Rentenversicherung (DRV)', ARRAY['At least 5 years of contributions (Wartezeit)','Retirement age reached (currently 66)','Foreign years may count via bilateral agreements']::text[], '{"forms":[{"code":"V0100","title":"Antrag auf Versichertenrente"},{"code":"V0800","title":"Anlage Ausland"}],"documents":["Valid passport or national ID","Residence permit (Aufenthaltstitel) if non-EU","Anmeldebestätigung (address registration)","Tax ID (Steuer-Identifikationsnummer)","Full CV with all employers","Bank account IBAN"],"proofs":["Foreign work history (translated)","Marriage / divorce certificates for Rentensplitting"]}'::jsonb, 'https://www.deutsche-rentenversicherung.de', NULL),
('erwerbsminderungsrente', 16, 'Reduced Earning Capacity Pension', 'Erwerbsminderungsrente', 'Pension when illness / disability makes working ≥ 6h/day impossible for ≥ 6 months.', '≈ 34–75 % of average net income', 'pension', 'Deutsche Rentenversicherung', ARRAY['At least 5 years of contributions incl. 3 years in the last 5','Medical earning capacity < 6 h/day (partial) or < 3 h/day (full)']::text[], '{"forms":[{"code":"R0100","title":"Antrag auf Erwerbsminderungsrente"},{"code":"S0050","title":"Selbsteinschätzungsbogen"}],"documents":["Valid passport or national ID","Residence permit (Aufenthaltstitel) if non-EU","Anmeldebestätigung (address registration)","Tax ID (Steuer-Identifikationsnummer)","All medical reports (Ärztliche Befundberichte)"],"proofs":["Krankenkasse Krankengeld notice","Rehabilitation reports"]}'::jsonb, NULL, NULL),
('hinterbliebenenrente', 17, 'Survivors'' Pension', 'Witwen-/Witwer-/Waisenrente', 'Pension for spouses and children after the insured person dies.', '55 % (large) or 25 % (small) of deceased pension', 'pension', 'Deutsche Rentenversicherung', ARRAY['Deceased had 5+ contribution years','Marriage lasted ≥ 1 year (or died from accident)','Children under 18 (27 if in education)']::text[], '{"forms":[{"code":"R0500","title":"Antrag auf Hinterbliebenenrente"},{"code":"R0660","title":"Anlage Kinder für Waisenrente"}],"documents":["Valid passport or national ID","Residence permit (Aufenthaltstitel) if non-EU","Anmeldebestätigung (address registration)","Tax ID (Steuer-Identifikationsnummer)","Marriage certificate","Death certificate (Sterbeurkunde)"],"proofs":["Deceased''s insurance number (Rentenversicherungsnummer)","School certificate for orphans 18–27"]}'::jsonb, NULL, NULL),
('schwerbehindertenausweis', 18, 'Severe Disability ID', 'Schwerbehindertenausweis (GdB ≥ 50)', 'Official ID granting workplace protection, tax relief and travel discounts.', NULL, 'disability', 'Versorgungsamt / Landesamt für Soziales', ARRAY['Long-term (> 6 months) impairment','Grad der Behinderung (GdB) of at least 50']::text[], '{"forms":[{"code":"SchwbG-Antrag","title":"Antrag auf Feststellung einer Behinderung"},{"code":"Verlängerung","title":"Verlängerungsantrag alle 5 Jahre"}],"documents":["Valid passport or national ID","Residence permit (Aufenthaltstitel) if non-EU","Anmeldebestätigung (address registration)","Tax ID (Steuer-Identifikationsnummer)","Passport photo (35×45 mm)"],"proofs":["All doctor and hospital reports (Befundberichte, Entlassungsbriefe)","Psychological / psychiatric reports if applicable","List of treating doctors with contact details"]}'::jsonb, NULL, 'Merkzeichen (G, aG, B, H, RF, BI, TBl) unlock additional entitlements — request explicitly.'),
('behinderten_pauschbetrag', 19, 'Disability Tax Allowance', 'Behinderten-Pauschbetrag', 'Fixed tax-free amount (€384–€7,400) based on Grad der Behinderung.', NULL, 'tax', 'Finanzamt', ARRAY['Recognised GdB of at least 20','Documented in Schwerbehindertenausweis or Bescheid']::text[], '{"forms":[{"code":"Anlage außergewöhnliche Belastungen","title":"Anlage aB zur Einkommensteuer"}],"documents":["Valid passport or national ID","Residence permit (Aufenthaltstitel) if non-EU","Anmeldebestätigung (address registration)","Tax ID (Steuer-Identifikationsnummer)","Copy of Schwerbehindertenausweis"],"proofs":["Feststellungsbescheid Versorgungsamt"]}'::jsonb, NULL, NULL),
('blindengeld', 20, 'Blind Persons'' Allowance', 'Blindengeld / Landesblindengeld', 'State allowance for blind or highly visually-impaired people (varies by Bundesland).', '€400–€800 (state-dependent)', 'disability', 'Landesamt für Soziales / Versorgungsamt', ARRAY['Merkzeichen BI (blind) or TBl (deaf-blind)','Ordinary residence in the Bundesland']::text[], '{"forms":[{"code":"Blindengeld-Antrag","title":"Antrag Landesblindengeld"}],"documents":["Valid passport or national ID","Residence permit (Aufenthaltstitel) if non-EU","Anmeldebestätigung (address registration)","Tax ID (Steuer-Identifikationsnummer)","Copy of Schwerbehindertenausweis with Merkzeichen BI/TBl"],"proofs":["Augenärztliches Gutachten (ophthalmologist''s report)"]}'::jsonb, NULL, NULL),
('eingliederungshilfe', 21, 'Disability Integration Support', 'Eingliederungshilfe (SGB IX)', 'Individualised support to enable participation — assistance, aids, therapies, workshop.', NULL, 'disability', 'Bezirk / Landkreis (Eingliederungshilfeträger)', ARRAY['Physical, mental or intellectual disability with participation restriction','Support need not covered by other insurance']::text[], '{"forms":[{"code":"EGH-Antrag","title":"Antrag auf Leistungen der Eingliederungshilfe"}],"documents":["Valid passport or national ID","Residence permit (Aufenthaltstitel) if non-EU","Anmeldebestätigung (address registration)","Tax ID (Steuer-Identifikationsnummer)","Copy of Schwerbehindertenausweis if any"],"proofs":["Medical / psychological reports","Bedarfsermittlung (support-needs assessment)","Income & assets proof (contribution assessment)"]}'::jsonb, NULL, NULL),
('krankengeld', 22, 'Statutory Sick Pay', 'Krankengeld (GKV)', '70 % of gross (max 90 % net) from week 7 of continuous illness, up to 78 weeks.', 'up to €120 / day', 'illness', 'Statutory Krankenkasse', ARRAY['Statutorily insured with Krankengeld entitlement','Certified sick > 6 weeks (after employer''s Lohnfortzahlung)','Same diagnosis: 78 weeks within 3 years']::text[], '{"forms":[{"code":"AU-Bescheinigung","title":"Arbeitsunfähigkeitsbescheinigung (elektronisch)"},{"code":"Krankengeld-Antrag","title":"Antrag & Fragebogen der Krankenkasse"}],"documents":["Valid passport or national ID","Residence permit (Aufenthaltstitel) if non-EU","Anmeldebestätigung (address registration)","Tax ID (Steuer-Identifikationsnummer)","Health insurance card"],"proofs":["Continuous AU-Bescheinigungen without gap","Last payslip for base calculation"]}'::jsonb, NULL, NULL),
('verletztengeld', 23, 'Work-Injury Sick Pay', 'Verletztengeld', 'Sick pay after a work accident or recognised occupational disease (paid by BG).', 'up to 80 % of gross earnings', 'illness', 'Berufsgenossenschaft (BG) / Unfallkasse', ARRAY['Recognised Arbeitsunfall or Berufskrankheit','Arbeitsunfähig due to that event']::text[], '{"forms":[{"code":"Unfallanzeige","title":"Unfallanzeige (Arbeitgeber)"},{"code":"D-Arzt-Bericht","title":"Durchgangsarzt-Bericht"}],"documents":["Valid passport or national ID","Residence permit (Aufenthaltstitel) if non-EU","Anmeldebestätigung (address registration)","Tax ID (Steuer-Identifikationsnummer)","Health insurance card"],"proofs":["Accident report","Witness statements","All medical records"]}'::jsonb, NULL, NULL),
('reha', 24, 'Medical Rehabilitation', 'Medizinische Rehabilitation (Reha)', '3–6 weeks of inpatient/outpatient rehab paid by DRV or Krankenkasse.', NULL, 'illness', 'Deutsche Rentenversicherung or Krankenkasse', ARRAY['Chronic illness / after severe treatment','6 months of pension contributions in last 24 months (DRV)']::text[], '{"forms":[{"code":"G0100","title":"Antrag auf Leistungen zur medizinischen Reha (DRV)"},{"code":"S0050","title":"Selbsteinschätzung"},{"code":"G0200","title":"Ärztlicher Befundbericht"}],"documents":["Valid passport or national ID","Residence permit (Aufenthaltstitel) if non-EU","Anmeldebestätigung (address registration)","Tax ID (Steuer-Identifikationsnummer)","Rentenversicherungsnummer / Krankenkasse card"],"proofs":["Doctor''s Befundbericht","Prior clinic reports"]}'::jsonb, NULL, NULL),
('haushaltshilfe', 25, 'Household Help', 'Haushaltshilfe (GKV)', 'Paid household support when a parent can''t run the home due to illness / hospital stay.', NULL, 'illness', 'Krankenkasse', ARRAY['Illness, hospital or Reha stay of insured person','Child under 12 (or disabled) in household','No adult in household can take over']::text[], '{"forms":[{"code":"Haushaltshilfe-Antrag","title":"Antrag Haushaltshilfe der Krankenkasse"}],"documents":["Valid passport or national ID","Residence permit (Aufenthaltstitel) if non-EU","Anmeldebestätigung (address registration)","Tax ID (Steuer-Identifikationsnummer)","Health insurance card"],"proofs":["Ärztliche Bescheinigung on inability to run household","Proof child lives in household (Meldebescheinigung)"]}'::jsonb, NULL, NULL),
('pflegegrad', 26, 'Care Level Assessment', 'Pflegegrad 1–5 (MDK-Begutachtung)', 'Assessment that unlocks Pflegegeld, care aids, day-care and residential support.', NULL, 'care', 'Pflegekasse (attached to Krankenkasse)', ARRAY['Support need expected > 6 months','Pre-insurance ≥ 2 of last 10 years']::text[], '{"forms":[{"code":"Pflegegrad-Antrag","title":"Antrag auf Leistungen der Pflegeversicherung"}],"documents":["Valid passport or national ID","Residence permit (Aufenthaltstitel) if non-EU","Anmeldebestätigung (address registration)","Tax ID (Steuer-Identifikationsnummer)","List of treating doctors","Medication plan"],"proofs":["Pflegetagebuch (7-day care diary)","Recent hospital / doctor reports"]}'::jsonb, NULL, 'MDK visit follows within 25 working days. Prepare the Pflegetagebuch beforehand.'),
('pflegegeld', 27, 'Care Allowance (Home Care)', 'Pflegegeld', 'Cash allowance paid to the insured when family / friends provide the care.', '€347 (PG2) → €990 (PG5)', 'care', 'Pflegekasse', ARRAY['Recognised Pflegegrad 2–5','Care provided at home (not fully residential)']::text[], '{"forms":[{"code":"Pflegegeld-Erklärung","title":"Erklärung zur Auszahlung an Pflegeperson"}],"documents":["Valid passport or national ID","Residence permit (Aufenthaltstitel) if non-EU","Anmeldebestätigung (address registration)","Tax ID (Steuer-Identifikationsnummer)","Pflegegrad-Bescheid"],"proofs":["Beratungsbesuch confirmation (every 6 months for PG2/3, 3 months for PG4/5)"]}'::jsonb, NULL, NULL),
('verhinderungspflege', 28, 'Substitute Care', 'Verhinderungspflege', 'Up to 6 weeks / year replacement care when main carer is on holiday or ill.', 'up to €1,612 / year (+ Kurzzeitpflege budget)', 'care', 'Pflegekasse', ARRAY['Pflegegrad 2–5','Main carer cared at least 6 months already']::text[], '{"forms":[{"code":"Verhinderungspflege-Antrag","title":"Antrag Verhinderungspflege"}],"documents":["Valid passport or national ID","Residence permit (Aufenthaltstitel) if non-EU","Anmeldebestätigung (address registration)","Tax ID (Steuer-Identifikationsnummer)","Invoice / receipts of the substitute carer or service"],"proofs":["Confirmation from Pflegedienst or private carer"]}'::jsonb, NULL, NULL),
('arbeitslosengeld1', 29, 'Unemployment Insurance', 'Arbeitslosengeld I (ALG I)', '60 % (67 % with child) of last net income for 6–24 months after redundancy.', 'up to ≈ €2,900', 'unemployment', 'Agentur für Arbeit', ARRAY['12+ months of unemployment insurance in the last 30 months','Registered as arbeitsuchend within 3 days of contract end','Available for at least 15 h/week work']::text[], '{"forms":[{"code":"Alg-Antrag","title":"Antrag auf Arbeitslosengeld (online)"},{"code":"Arbeitsbescheinigung","title":"Arbeitsbescheinigung des Arbeitgebers"}],"documents":["Valid passport or national ID","Residence permit (Aufenthaltstitel) if non-EU","Anmeldebestätigung (address registration)","Tax ID (Steuer-Identifikationsnummer)","Steuer-ID","Sozialversicherungsausweis","Bank account IBAN"],"proofs":["Kündigung / Aufhebungsvertrag","Payslips of last 12 months","CV & Arbeitszeugnisse"]}'::jsonb, 'https://www.arbeitsagentur.de/arbeitslos-arbeit-finden/arbeitslosengeld', NULL),
('steuerklassenwechsel', 30, 'Tax Bracket Change', 'Steuerklassenwechsel', 'Switch classes (III/V, IV/IV or IV + Faktor) to lower monthly wage tax for couples.', NULL, 'tax', 'Finanzamt', ARRAY['Married or in registered civil partnership','Both spouses tax-resident in Germany']::text[], '{"forms":[{"code":"Steuerklassenwechsel-Antrag","title":"Antrag Steuerklassenwechsel bei Ehegatten"}],"documents":["Valid passport or national ID","Residence permit (Aufenthaltstitel) if non-EU","Anmeldebestätigung (address registration)","Tax ID (Steuer-Identifikationsnummer)","Marriage certificate (translated)"],"proofs":["Latest ELStAM data"]}'::jsonb, NULL, NULL),
('kinderfreibetrag', 31, 'Child Tax Allowance', 'Kinderfreibetrag', 'Tax-free allowance (€9,540 / child in 2026) — Finanzamt applies whichever is more favourable vs Kindergeld.', NULL, 'tax', 'Finanzamt', ARRAY['Eligible for Kindergeld','Filing income-tax return']::text[], '{"forms":[{"code":"Anlage Kind","title":"Anlage Kind"}],"documents":["Valid passport or national ID","Residence permit (Aufenthaltstitel) if non-EU","Anmeldebestätigung (address registration)","Tax ID (Steuer-Identifikationsnummer)","Child''s Steuer-ID"],"proofs":["Kindergeld-Bescheid"]}'::jsonb, NULL, NULL),
('pflege_pauschbetrag', 32, 'Care Tax Allowance', 'Pflege-Pauschbetrag', '€600–€1,800 / year tax-free for unpaid carers (based on Pflegegrad of the cared-for person).', NULL, 'tax', 'Finanzamt', ARRAY['You care for a close relative with Pflegegrad 2–5 unpaid at home']::text[], '{"forms":[{"code":"Anlage außergewöhnliche Belastungen","title":"Anlage aB"}],"documents":["Valid passport or national ID","Residence permit (Aufenthaltstitel) if non-EU","Anmeldebestätigung (address registration)","Tax ID (Steuer-Identifikationsnummer)","Cared person''s Pflegegrad-Bescheid"],"proofs":["Meldebescheinigung showing care at home"]}'::jsonb, NULL, NULL),
('doppelte_haushaltsfuehrung', 33, 'Double Household Deduction', 'Doppelte Haushaltsführung', 'Deduct up to €1,000 / month for a second residence at your workplace.', NULL, 'tax', 'Finanzamt', ARRAY['Main residence with own household outside workplace city','Second flat at workplace maintained for job reasons']::text[], '{"forms":[{"code":"Anlage N","title":"Anlage N — Werbungskosten"}],"documents":["Valid passport or national ID","Residence permit (Aufenthaltstitel) if non-EU","Anmeldebestätigung (address registration)","Tax ID (Steuer-Identifikationsnummer)","Rental contracts of both homes"],"proofs":["Monthly rent + utility invoices","Travel tickets home"]}'::jsonb, NULL, NULL),
('rundfunkbefreiung', 34, 'Broadcasting Fee Exemption', 'Rundfunkbeitrag-Befreiung', 'Exemption from the €18.36 / month ARD/ZDF/Deutschlandradio fee.', '€18.36 / month saving', 'social_insurance', 'Beitragsservice ARD ZDF Deutschlandradio', ARRAY['Recipient of Bürgergeld, Sozialhilfe, BAföG, Wohngeld (+ Kinderzuschlag)','Merkzeichen RF (deaf-blind or severe restriction)']::text[], '{"forms":[{"code":"Befreiungsantrag","title":"Antrag auf Befreiung / Ermäßigung"}],"documents":["Valid passport or national ID","Residence permit (Aufenthaltstitel) if non-EU","Anmeldebestätigung (address registration)","Tax ID (Steuer-Identifikationsnummer)"],"proofs":["Current benefit decision (Bescheid) or Schwerbehindertenausweis mit RF"]}'::jsonb, 'https://www.rundfunkbeitrag.de', NULL),
('sozialversicherungsausweis', 35, 'Social Insurance Number', 'Sozialversicherungsausweis / -nummer', 'Mandatory number issued once you start work — required by every employer.', NULL, 'social_insurance', 'Deutsche Rentenversicherung (via first employer or Krankenkasse)', ARRAY['Starting employment in Germany']::text[], '{"forms":[{"code":"Automatisch","title":"Issued automatically on first employment"}],"documents":["Valid passport or national ID","Residence permit (Aufenthaltstitel) if non-EU","Anmeldebestätigung (address registration)","Tax ID (Steuer-Identifikationsnummer)"],"proofs":["Employment contract"]}'::jsonb, NULL, NULL),
('krankenversicherung', 36, 'Health Insurance Enrolment', 'Krankenversicherung (GKV / PKV)', 'Mandatory health insurance — statutory (GKV) or private (PKV) depending on income & status.', NULL, 'social_insurance', 'Krankenkasse or Private Insurer', ARRAY['Living in Germany > 3 months','Employment, self-employment, study or family cover']::text[], '{"forms":[{"code":"GKV-Antrag","title":"Mitgliedsantrag Krankenkasse"},{"code":"PKV-Antrag","title":"Antrag Private Krankenversicherung"}],"documents":["Valid passport or national ID","Residence permit (Aufenthaltstitel) if non-EU","Anmeldebestätigung (address registration)","Tax ID (Steuer-Identifikationsnummer)","Employment contract or study enrolment","Previous insurance letter"],"proofs":["Income proof (self-employed / high earners)"]}'::jsonb, NULL, NULL);