
DO $do$
DECLARE
  cat_t uuid := (SELECT id FROM public.knowledge_categories WHERE slug='tax');
  cat_i uuid := (SELECT id FROM public.knowledge_categories WHERE slug='immigration');
  cat_e uuid := (SELECT id FROM public.knowledge_categories WHERE slug='education');
  cat_br uuid := (SELECT id FROM public.knowledge_categories WHERE slug='bereavement');
BEGIN

INSERT INTO public.knowledge_services (slug, category_id, name, short_description, eligibility, legal_basis, jurisdiction_notes, typical_timeline, official_fees, fees_detail, where_to_apply, delivery_playbook, required_documents, forms, online_portals, common_pitfalls, appeals_process, tips, requires_expert_role, status) VALUES

('elster-registration', cat_t, 'ELSTER registration',
 'Digital certificate to file every tax return, USt-Voranmeldung, Fragebogen zur steuerlichen Erfassung. Free service of the tax administration.',
 'Anyone with a Steuer-ID.',
 'AO §87a — elektronische Kommunikation.',
 'Federal.','Certificate 10–14 days by post (activation letter + code arrive separately).',
 'Free','Free. Third-party ELSTER services charge for what is free.',
 'elster.de.',
 jsonb_build_array(
   'Register on elster.de with Steuer-ID (personal) or Steuernummer (organisation)',
   'Wait for activation letter (Aktivierungs-ID) by post',
   'Second email with Aktivierungs-Code',
   'Combine to generate .pfx certificate file — store securely & backup',
   'Test-file a Freistellungsauftrag or empty ESt draft to verify credentials'),
 jsonb_build_array('Steuer-ID','Personal ID (name/address match ELSTER)'),
 jsonb_build_array(
   jsonb_build_object('name','Registration (Zertifikatsdatei)','who','Applicant','notes','Personal use — Steuer-ID based'),
   jsonb_build_object('name','Registration (Organisation)','who','Business owner','notes','Steuernummer based; for USt/Lohnsteuer')),
 jsonb_build_array(jsonb_build_object('label','ELSTER portal','url','https://www.elster.de/eportal/registrierung-auswahl/aktivierungslink')),
 jsonb_build_array(
   'Registering with wrong Steuer-ID vs Steuernummer → wrong certificate scope',
   'Losing the .pfx file → full re-registration; ~2 weeks lost'),
 'Administrative issue only.',
 'Register early — even before first tax obligation; the 2-week wait always bites in April.',
 'case_manager','active'),

('einkommensteuer', cat_t, 'Einkommensteuererklärung — Personal income tax return',
 'Annual personal income tax return. Mandatory in many cases (multiple employers, Elterngeld, side income, Steuerklasse III/V) and always worth filing for employees with commuting / home office / handwerker.',
 'Mandatory (Pflichtveranlagung §46 EStG) or voluntary (Antragsveranlagung — 4-year window).',
 'EStG; AO deadlines §149.',
 'Federal. Länder run Finanzämter.',
 'Filing deadline: 31 Jul following year (self-file); 30 Apr second year (Steuerberater); Bescheid 4–16 weeks after filing.',
 'Free','Free filing. Steuerberater fees per StBVV. Lohnsteuerhilfeverein €120–€400/yr (income-capped members).',
 'ELSTER (elster.de) or via Steuerberater.',
 jsonb_build_array(
   'Collect Lohnsteuerbescheinigung, rental income statements, Elterngeldbescheid, Krankenkassenbescheinigung',
   'Log all Werbungskosten: Pendlerpauschale, home-office, Fortbildung, Arbeitsmittel',
   'Log Sonderausgaben (Spenden, Kirchensteuer, private Altersvorsorge)',
   'Log außergewöhnliche Belastungen (health, Pflege, disability Pauschbetrag)',
   'File Mantelbogen + Anlage N/S/G/V/KAP via ELSTER',
   'Await Bescheid; check for typing errors; Einspruch within 1 month if wrong'),
 jsonb_build_array(
   'Steuer-ID','Lohnsteuerbescheinigung(s)','Bank statements (interest/dividends)',
   'Rental contracts / Nebenkosten','Handwerker/Haushaltsnahe invoices',
   'Spenden receipts','Krankheitskosten receipts','Elterngeldbescheid'),
 jsonb_build_array(
   jsonb_build_object('name','ESt 1 A Hauptvordruck','who','Taxpayer','notes','Mantelbogen'),
   jsonb_build_object('name','Anlage N','who','Employees','notes','Nichtselbständige Arbeit'),
   jsonb_build_object('name','Anlage S','who','Freelancers','notes','Selbständige Arbeit'),
   jsonb_build_object('name','Anlage G','who','Trade','notes','Gewerbebetrieb'),
   jsonb_build_object('name','Anlage V','who','Landlords','notes','Vermietung & Verpachtung'),
   jsonb_build_object('name','Anlage KAP','who','Investors','notes','Capital income'),
   jsonb_build_object('name','Anlage Vorsorgeaufwand','who','Everyone','notes','Health/pension'),
   jsonb_build_object('name','Anlage Kind','who','Parents','notes','Per child')),
 jsonb_build_array(jsonb_build_object('label','ELSTER Mein ELSTER','url','https://www.elster.de/eportal/formulare-leistungen/alleformulare')),
 jsonb_build_array(
   'Missing Pflichtveranlagung deadline → Verspätungszuschlag min. €25/month',
   'Overlooking Elterngeld Progressionsvorbehalt → surprise bill',
   'Non-EU residents: Splittingtabelle only with Bescheinigung EU/EWR — else Grundtabelle',
   'Working from home >100 days but forgot Home-Office Pauschale (€6/day, max €1 260)'),
 'Einspruch to Finanzamt within 1 month of Bescheid; then Finanzgericht.',
 'Run ESt with & without hypothetical Werbungskosten to know if collecting more receipts is worth it; automate with WISO or Steuerbot for straightforward cases.',
 'accountant','active'),

('freiberufler-registration', cat_t, 'Freiberufler / Kleinunternehmer registration',
 'Register a freelance activity with the Finanzamt via ''Fragebogen zur steuerlichen Erfassung'' to receive a Steuernummer and choose Kleinunternehmerregelung.',
 'Independent activity in a Katalogberuf (§18 EStG) — no Gewerbeanmeldung needed. Otherwise → Gewerbe.',
 'EStG §18; UStG §19; AO §138.',
 'Federal + Länder Finanzämter.',
 'Steuernummer 3–8 weeks after Fragebogen filed.',
 'Free','Free filing. Steuerberater ~€250–€600 for setup.',
 'Fragebogen zur steuerlichen Erfassung via ELSTER only (paper closed 2021).',
 jsonb_build_array(
   'Confirm activity is Freiberuflich (Katalogberuf) — else Gewerbe route (Ordnungsamt + IHK)',
   'Register ELSTER organisational account (or reuse personal)',
   'Complete Fragebogen zur steuerlichen Erfassung — 8 sections',
   'Decide Kleinunternehmer (§19 UStG: prior yr ≤€25k / forecast ≤€100k from 2025) vs Regelbesteuerung',
   'Await Steuernummer + assignment letter',
   'Set bookkeeping (EÜR §4(3)), open business account, plan quarterly Einkommensteuervorauszahlungen',
   'If Regelbesteuerung: monthly/quarterly USt-Voranmeldung; annual USt-Erklärung + EÜR + ESt'),
 jsonb_build_array(
   'Steuer-ID','Personal ID','Anmeldebestätigung',
   'Professional qualification / diploma proof','Client contracts / letters of intent (income estimate)'),
 jsonb_build_array(
   jsonb_build_object('name','Fragebogen zur steuerlichen Erfassung','who','Applicant','notes','ELSTER only'),
   jsonb_build_object('name','Anlage EÜR','who','Annual','notes','Einnahmen-Überschuss-Rechnung'),
   jsonb_build_object('name','USt 1 A — Umsatzsteuer-Voranmeldung','who','Monthly/Quarterly','notes','If not Kleinunternehmer'),
   jsonb_build_object('name','USt 2 A — Umsatzsteuer-Erklärung','who','Annual','notes','Both regimes')),
 jsonb_build_array(jsonb_build_object('label','ELSTER — Fragebogen','url','https://www.elster.de/eportal/formulare-leistungen/alleformulare/fsehr')),
 jsonb_build_array(
   'Wrong classification Freiberufler vs Gewerbe → Gewerbesteuer backdated + IHK fees',
   'Kleinunternehmer forgets Vorjahresumsatz check → auto-flip to Regelbesteuerung',
   'International B2B invoices missing Reverse-Charge note (§13b UStG)',
   'Estimated income too low → Nachzahlung + increased Vorauszahlung in Y2'),
 'Einspruch to Finanzamt within 1 month; Finanzgericht for tax disputes.',
 'Always help clients open a separate business account & simple bookkeeping (sevDesk, Lexoffice) at registration — avoids year-end chaos.',
 'accountant','active'),

('ust-voranmeldung', cat_t, 'Umsatzsteuer-Voranmeldung (VAT return)',
 'Monthly or quarterly VAT filing via ELSTER. Difference between USt on sales and Vorsteuer on purchases is paid or refunded.',
 'Regelbesteuerung businesses (not Kleinunternehmer §19 UStG).',
 'UStG §18; frequency §18(2) UStG.',
 'Federal.',
 'Filing deadline: 10th of following month/quarter; Dauerfristverlängerung +1 month.',
 'Free','No fee. Dauerfristverlängerung requires 1/11 Sondervorauszahlung (annual, refunded).',
 'ELSTER.',
 jsonb_build_array(
   'Determine frequency: >€7 500 tax/year → monthly',
   'Book Dauerfristverlängerung via USt 1 H if extra month needed',
   'Sum taxable turnover (7 % / 19 %), Vorsteuer, intra-EU acquisitions',
   'File USt 1 A via ELSTER by 10th (or 10th + 1 month)',
   'Pay Zahllast via SEPA Lastschrift or bank transfer',
   'Reconcile annually in USt-Erklärung; correct earlier periods via §153 AO Berichtigung'),
 jsonb_build_array('Sales register (invoices out)','Purchase register (invoices in)','Bank statements','Cash book (retail)','Intra-EU statements & VAT IDs'),
 jsonb_build_array(
   jsonb_build_object('name','USt 1 A Voranmeldung','who','Business','notes','Monthly/Quarterly'),
   jsonb_build_object('name','USt 1 H Dauerfristverlängerung','who','Business','notes','Grants +1 month'),
   jsonb_build_object('name','Zusammenfassende Meldung (ZM)','who','Intra-EU seller','notes','BZSt-Online monthly by 25th')),
 jsonb_build_array(jsonb_build_object('label','ELSTER — USt Voranmeldung','url','https://www.elster.de/eportal/formulare-leistungen/alleformulare/usthoehe')),
 jsonb_build_array(
   'Late filing → Verspätungszuschlag + Säumniszuschläge 1 %/month',
   'Reverse-Charge invoices booked with 19 % → double VAT',
   'Kleinunternehmer above threshold mid-year — mandatory switch next Jan, no gradual'),
 'Einspruch within 1 month; Finanzgericht.',
 'Automate via Lexoffice / sevDesk — DATEV-format ELSTER submission saves 30 min per month and cuts errors.',
 'accountant','active'),

('aufenthaltstitel-verlaengerung', cat_i, 'Aufenthaltstitel — extension',
 'Extension of an existing residence permit (Blue Card, §16b, §18a/b, §21, §23a, §28, §33, §34 etc.). File 6–8 weeks before expiry to secure Fiktionsbescheinigung.',
 'Holders of a valid Aufenthaltstitel about to expire; residence purpose still fulfilled.',
 'AufenthG §81 (Fiktionswirkung §81(4)) + purpose-specific §s.',
 'Länder-run Ausländerbehörden; digital portals in Berlin, Hamburg, München; paper in others.',
 '4–16 weeks; Fiktionsbescheinigung immediately.',
 '€93–€100 (extension); €133 permanent',
 'Extension usually €93 (€100 first issuance). Reduced for children, refugees, Türken §Assoc.-Beschluss 1/80.',
 'Ausländerbehörde of Anmeldung district.',
 jsonb_build_array(
   'Diarise expiry 8 weeks before — apply early to trigger Fiktionsbescheinigung',
   'Confirm purpose still valid (employment / study / family) with fresh proofs',
   'Book appointment via city portal (Berlin ABH Termin, München S-BA, HH online)',
   'Submit Antrag + biometrics + fee; receive Fiktionsbescheinigung',
   'Provide any Nachforderungen within given deadline',
   'Collect eAT card; update employer, Krankenkasse, Meldebehörde'),
 jsonb_build_array(
   'Current passport (≥6 months validity)','Existing eAT','Anmeldebestätigung',
   'Biometric photo (35×45, EU norm)',
   'Employment contract / payslips / study certificate / family ties proof',
   'Krankenversicherungsnachweis','Housing proof (rental contract + Wohnungsgeberbestätigung)'),
 jsonb_build_array(
   jsonb_build_object('name','Antrag auf Erteilung/Verlängerung eines Aufenthaltstitels','who','Applicant','notes','Ausländerbehörde form'),
   jsonb_build_object('name','Erklärung zum Beschäftigungsverhältnis','who','Employer','notes','For §18/§19c/§18b'),
   jsonb_build_object('name','Zusatzblatt A — Familienangehörige','who','Family cases','notes',''),
   jsonb_build_object('name','Verpflichtungserklärung §68','who','Sponsor','notes','If dependants join')),
 jsonb_build_array(
   jsonb_build_object('label','Berlin ABH — Termin','url','https://otv.verwalt-berlin.de/'),
   jsonb_build_object('label','München ABH','url','https://stadt.muenchen.de/service/info/kreisverwaltungsreferat/1069577/')),
 jsonb_build_array(
   'Applying after expiry → illegal stay, fines, negative record',
   'Blue Card salary drop below threshold (2026 ~€48 300; Mangelberuf ~€43 500) — refusal',
   'Family reunion cases missing A1 / B1 Deutsch → refusal §30 AufenthG',
   'Insufficient housing (per person m²) → refusal for family reunion'),
 'Klage to Verwaltungsgericht within 1 month of Ablehnung; parallel Eilantrag §80(5) VwGO to keep stay.',
 'Encourage clients to keep a ''renewal folder'' updated quarterly — Bundesland ABHs often have zero flexibility on missing docs.',
 'lawyer','active'),

('einbuergerung', cat_i, 'Einbürgerung — Naturalisation',
 'German citizenship. 2024 reform: 5-year residence (3 for high integration), dual citizenship allowed, B1 German + Einbürgerungstest, no reliance on welfare (with exceptions).',
 '5 years (or 3 for besondere Integrationsleistungen), unbefristetes Aufenthaltsrecht, B1 Deutsch, Einbürgerungstest, secure livelihood, no serious criminal record, commitment to freiheitliche demokratische Grundordnung.',
 'StAG — 2024 reform (StARModG).',
 'Länder execute; Einbürgerungsbehörde of the Kommune.',
 '12–36 months depending on Bundesland backlog.',
 '€255 adult / €51 minor with parent',
 '€255 adult; €51 minor if applying with parent; €255 minor alone. Payable on submission or acceptance depending on Land.',
 'Einbürgerungsbehörde of Wohnsitz.',
 jsonb_build_array(
   'Pre-check eligibility (residence years, income, language, tests)',
   'Book Einbürgerungstest (VHS, ~€25); pass 17/33',
   'Obtain B1 Deutsch certificate (Goethe/telc/ÖSD/BAMF Kurs)',
   'Collect Lebenslauf + income proof + Rentenverlauf + Führungszeugnis',
   'Submit Antrag with children (Miteinbürgerung §10 StAG)',
   'Attend Erwartungsgespräch / Feierstunde; receive Einbürgerungsurkunde',
   'Update passport & Meldebehörde; deregister prior citizenship only if home country demands'),
 jsonb_build_array(
   'Passport(s) + all prior residence titles',
   'Geburtsurkunde with Apostille + translation',
   'Marriage / divorce certs with Apostille',
   'Anmeldebestätigung + last 8 years address history',
   'B1 certificate + Einbürgerungstest',
   'Income: 12 months payslips or Steuerbescheide (self-employed)',
   'Rentenverlauf (DRV V0100)','Führungszeugnis (issued to Einbürgerungsbehörde)'),
 jsonb_build_array(
   jsonb_build_object('name','Antrag auf Einbürgerung','who','Applicant (per adult)','notes','Bundesland-specific'),
   jsonb_build_object('name','Miteinbürgerung Kind','who','Parent','notes','Attached to Hauptantrag'),
   jsonb_build_object('name','Loyalitätserklärung','who','Applicant','notes','Freiheitliche demokratische Grundordnung'),
   jsonb_build_object('name','Verzichtserklärung / Beibehaltungsgenehmigung','who','If needed','notes','Home-country dependent')),
 jsonb_build_array(jsonb_build_object('label','BAMF — Einbürgerungstest','url','https://www.bamf.de/DE/Themen/Integration/ZugewanderteTeilnehmende/Einbuergerung/einbuergerung-node.html')),
 jsonb_build_array(
   'Aufstockendes Bürgergeld disqualifies unless refugee / not self-inflicted (2024 reform tightened)',
   'Criminal record: 90 Tagessätze / 3 months Freiheit lifetime disqualification (small offences aggregated)',
   'Assuming automatic dual — some countries (India, China) still force renunciation'),
 'Untätigkeitsklage after 3 months without decision (§75 VwGO); Klage against refusal to Verwaltungsgericht within 1 month.',
 'Prepare Einbürgerungstest and B1 6–9 months before eligibility date — they are the tasks clients delay most.',
 'lawyer','active'),

('kita-anmeldung', cat_e, 'Kita-Anmeldung & Betreuungsplatz',
 'Every child from age 1 has a Rechtsanspruch on a Kita place (§24 SGB VIII). Slots scarce in metros — apply in parallel to many Kitas + city portal.',
 'Child ≥1 year (from 3 years: half-day guaranteed). Some Länder cover from birth.',
 'SGB VIII §24; Länder Kitagesetze.',
 'Länder + Kommune specific portals (Kita-Navigator NRW, Berlin Kita-Navigator, Little Bird BW/Bayern).',
 'Apply 6–12 months before desired start; slot decisions Feb–May for August starts.',
 'Free portal','Portal free. Kita fees Länder-specific: Berlin free, NRW income-based, Bayern up to €150/mo.',
 'Municipal Kita portal + individual Kita visits.',
 jsonb_build_array(
   'Register on city portal (Berlin Kita-Navigator / Little Bird / Kita.de)',
   'Visit at least 5–10 Kitas; note director''s email',
   'Get Kita-Gutschein / Bedarfsbescheinigung from Jugendamt (Berlin: after slot; NRW: not needed)',
   'Submit acceptance & Betreuungsvertrag; register income for fee bracket',
   'File change with Familienkasse (Kinderzuschlag) if fees affect income',
   'If no slot by Rechtsanspruch date: file Anmeldung + Abmahnung to Jugendamt; document Schadensersatz claim'),
 jsonb_build_array(
   'Geburtsurkunde','Anmeldebestätigung',
   'Impfausweis (Masern-Nachweis §20 IfSG mandatory)',
   'Proof of parents'' employment / studies',
   'U-Untersuchungen booklet','Income proof (fee assessment)'),
 jsonb_build_array(
   jsonb_build_object('name','Kita-Anmeldung','who','Parents','notes','Portal or PDF per Kita'),
   jsonb_build_object('name','Kita-Gutschein / Bedarfsbescheinigung','who','Parents','notes','Jugendamt'),
   jsonb_build_object('name','Betreuungsvertrag','who','Parents + Kita','notes','Includes probation, notice, fee bracket')),
 jsonb_build_array(
   jsonb_build_object('label','Berlin Kita-Navigator','url','https://kita-navigator.berlin.de/'),
   jsonb_build_object('label','Little Bird (BY, BW, NRW…)','url','https://portal.little-bird.de/')),
 jsonb_build_array(
   'Missing Masern-Impfung proof — legal refusal since 2020',
   'Applying only 2 months before start — no chance in metros',
   'Waiting for Jugendamt Gutschein before accepting Kita slot — some Kitas revoke'),
 'Formal complaint to Jugendamt then Verwaltungsgericht (Eilantrag) for Rechtsanspruch enforcement + Schadensersatz (childminder costs).',
 'Escalation letter template ready — after 3 months without slot, the Eilantrag route is the fastest lever.',
 'case_manager','active'),

('anerkennung-abschluss', cat_e, 'Anerkennung ausländischer Abschlüsse',
 'Recognition of foreign professional qualifications. Regulated professions (medicine, teaching, engineering titles) mandatory; unregulated voluntary for salary/visa uplift.',
 'Anyone with a foreign qualification wanting to work or get residence title on that basis.',
 'BQFG (Bundesberufsqualifikationsfeststellungsgesetz); Länder BQFG for teachers/health.',
 'Regulated profession → sector authority (Approbationsbehörde for doctors; Landesärztekammer). Non-regulated → IHK FOSA / HWK.',
 '3–4 months if complete; medical Approbation 6–12 months.',
 '€100–€600','IHK FOSA €100–€600; Approbation up to €1 000+; Kenntnisprüfung ~€400 extra; language test ~€250.',
 'Recognition finder (anerkennung-in-deutschland.de) → responsible authority.',
 jsonb_build_array(
   'Use ''Recognition Finder'' to identify authority',
   'Collect diploma + transcripts + syllabus + work certificates (translated & apostilled)',
   'Submit application with fee',
   'Await Gleichwertigkeitsbescheid: full / partial / negative',
   'For partial: complete Anpassungslehrgang or Eignungsprüfung',
   'For medicine: apply Berufserlaubnis while completing Kenntnisprüfung/Fachsprachprüfung; then Approbation'),
 jsonb_build_array(
   'Passport / ID',
   'Diploma + transcripts (Apostille + sworn translation)',
   'Syllabus / hours breakdown','Work certificates',
   'Language certificate (B2/C1 depending on profession)'),
 jsonb_build_array(
   jsonb_build_object('name','Antrag auf Feststellung der Gleichwertigkeit','who','Applicant','notes','IHK FOSA / HWK / sector authority'),
   jsonb_build_object('name','Antrag auf Approbation','who','Applicant','notes','Landes-Approbationsbehörde'),
   jsonb_build_object('name','Antrag auf Berufserlaubnis','who','Doctor','notes','Interim, valid up to 2 yrs')),
 jsonb_build_array(
   jsonb_build_object('label','Recognition Finder','url','https://www.anerkennung-in-deutschland.de/tools/berater/de/'),
   jsonb_build_object('label','IHK FOSA','url','https://www.ihk-fosa.de/')),
 jsonb_build_array(
   'Applying without translations — Länder reject on receipt',
   'Doctors underestimating Fachsprachprüfung difficulty',
   'Teachers assuming BQFG covers Länder rules — each Land runs its own procedure'),
 'Widerspruch to authority within 1 month; then Verwaltungsgericht.',
 'For Blue Card cases, chase Teilanerkennung explicitly — it can unlock §18a with Bildungspaket even before full recognition.',
 'lawyer','active'),

('fuehrerschein-umschreibung', cat_e, 'Führerschein-Umschreibung',
 'Convert a foreign driving licence to a German one. Full recognition, partial recognition, or full theory+practice depending on country of issue.',
 'Any resident with a valid foreign licence, resident in DE >6 months.',
 'FeV (Fahrerlaubnis-Verordnung) §29–31.',
 'Länder Führerscheinstellen. EU/EEA licences fully valid; other countries case-by-case.',
 '6–12 weeks (Umtausch); +3–6 months if theory+practice needed.',
 '€35–€200','Umtausch €35–€45; theory test €22 + tuition; practice test €120+. Sehtest €7, Erste-Hilfe €35.',
 'Führerscheinstelle of Wohnsitz.',
 jsonb_build_array(
   'Classify country: EU/EEA (auto), Anlage-11-A (full swap), Anlage-11-B (theory only), Anlage-11-C (theory+practice), rest (full)',
   'Book Sehtest + Erste-Hilfe-Kurs',
   'Submit Antrag with Übersetzung (ADAC/court-sworn) if needed',
   'Take theory / practical exams if class dictates',
   'Return original foreign licence at issuance of German Führerschein'),
 jsonb_build_array('Passport / ID','Anmeldebestätigung','Original foreign licence (+ sworn translation)','Biometric photo','Sehtest','Erste-Hilfe-Kurs certificate'),
 jsonb_build_array(jsonb_build_object('name','Antrag auf Erteilung / Umschreibung Fahrerlaubnis','who','Applicant','notes','Führerscheinstelle form')),
 jsonb_build_array(jsonb_build_object('label','BMDV — Führerscheinumtausch','url','https://www.bmv.de/DE/Themen/Verkehr/Strassen/Fuehrerschein/fuehrerschein.html')),
 jsonb_build_array(
   'Missing 6-month deadline for EU visitors → treated as ''ohne Fahrerlaubnis''',
   'Category downgrade (e.g. B automatic-only stamp) not spotted',
   'Foreign country not on Anlage 11 → complete lessons + exams'),
 'Widerspruch within 1 month; Verwaltungsgericht.',
 'Book Sehtest and Erste-Hilfe on Day 1 — clients always leave these until the appointment week.',
 'case_manager','active'),

('islamic-funeral', cat_br, 'Islamic funeral & repatriation',
 'Full Islamic burial in Germany within 48h, or repatriation to home country. Beistand coordinates Standesamt, Krankenhaus, funeral partner, mosque, consulate.',
 'Deceased Muslim (or family request Islamic rites). Available for all religions with parallel SOPs.',
 'Bestattungsgesetze der Länder; PStG for civil registration; ICAO/IATA rules for repatriation.',
 'Ruhezeit & burial timeframes differ. Berlin, NRW allow Sarglose Bestattung; Bavaria requires coffin. Islamic Grabfelder in most metros.',
 '24–72h in Germany; 3–7 days for repatriation depending on consulate.',
 '€3 500–€9 000 in DE; €5 000–€12 000 repatriation',
 'Bestattung DE: Grab/Grabnutzung, Sarg/Leichentuch, Waschung, Transport, Standesamt fees. Repatriation adds embalming, Zinksarg, air cargo, consulate fees.',
 'Beistand case manager coordinates; funeral partner handles hands-on rites.',
 jsonb_build_array(
   'Take intake: family contact, deceased''s citizenship, wishes (DE burial vs repatriation), insurance',
   'Assign funeral partner (Islamic, DITIB or independent)',
   'Standesamt Sterbeurkunde within 3 working days',
   'For DE burial: reserve Islamic Grabfeld; arrange Ghusl at Waschraum; Janazah at mosque; Bestattung',
   'For repatriation: apply for Leichenpass + Zinksarg sealing; embassy/consulate paperwork; airline coordination',
   'Notify Krankenkasse, DRV, employer, banks; issue estate SOP to family',
   'Post-funeral: file Sterbevierteljahr (spouse), Waisenrente (children), Bestattungsbeihilfe (Sozialamt if hilfebedürftig)'),
 jsonb_build_array(
   'Todesbescheinigung (doctor)','Passport of deceased','Anmeldebestätigung of deceased',
   'Marriage certificate of surviving spouse',
   'For repatriation: consular Leichenpass','Insurance policy documents (Sterbegeldversicherung)'),
 jsonb_build_array(
   jsonb_build_object('name','Anzeige eines Sterbefalls','who','Family / funeral director','notes','Standesamt'),
   jsonb_build_object('name','Antrag auf Leichenpass','who','Funeral director','notes','Consulate; needed for air transport'),
   jsonb_build_object('name','Antrag auf Bestattungsbeihilfe (§74 SGB XII)','who','Family','notes','If hilfebedürftig — Sozialamt pays reasonable costs'),
   jsonb_build_object('name','Antrag auf Erbschein','who','Heirs','notes','Nachlassgericht; for real-estate/banks')),
 jsonb_build_array(jsonb_build_object('label','ZMD — Islamic guidance','url','https://www.zmd.de/')),
 jsonb_build_array(
   'Family accepting inheritance before verifying debts — 6-week Ausschlagung window missed',
   'Consulate refuses Leichenpass without embalming certificate — plan embalming from Day 1',
   'Sozialamt rejects Bestattungsbeihilfe because heirs paid privately first — apply BEFORE payment'),
 'Sozialamt refusal → Widerspruch within 1 month, then Sozialgericht. Bestattungsgesetz disputes → Verwaltungsgericht.',
 'Assign a bilingual case manager on Day 1 and share the consulate-specific document checklist with the family before they visit the mosque.',
 'funeral_director','active')

ON CONFLICT (slug) DO UPDATE SET
  name=EXCLUDED.name, short_description=EXCLUDED.short_description,
  eligibility=EXCLUDED.eligibility, legal_basis=EXCLUDED.legal_basis,
  jurisdiction_notes=EXCLUDED.jurisdiction_notes, typical_timeline=EXCLUDED.typical_timeline,
  official_fees=EXCLUDED.official_fees, fees_detail=EXCLUDED.fees_detail,
  where_to_apply=EXCLUDED.where_to_apply,
  delivery_playbook=EXCLUDED.delivery_playbook, required_documents=EXCLUDED.required_documents,
  forms=EXCLUDED.forms, online_portals=EXCLUDED.online_portals,
  common_pitfalls=EXCLUDED.common_pitfalls, appeals_process=EXCLUDED.appeals_process,
  tips=EXCLUDED.tips, requires_expert_role=EXCLUDED.requires_expert_role;

END $do$;
